// This file was auto-generated by Fern from our API Definition.

import type * as Testcharmvision from "../index.js";

export interface BranchConditionYaml {
    criteria?: Testcharmvision.BranchCriteriaYaml;
    next_block_label?: string;
    description?: string;
    is_default?: boolean;
}
