// This file was auto-generated by Fern from our API Definition.

/** Supported file content encodings. */
export const FileEncoding = {
    Base64: "base64",
    Utf8: "utf-8",
} as const;
export type FileEncoding = (typeof FileEncoding)[keyof typeof FileEncoding];
