// This file was auto-generated by Fern from our API Definition.

import type * as Testcharmvision from "../index.js";

export type GetRunResponse =
    | Testcharmvision.GetRunResponse.TaskV1
    | Testcharmvision.GetRunResponse.TaskV2
    | Testcharmvision.GetRunResponse.OpenaiCua
    | Testcharmvision.GetRunResponse.AnthropicCua
    | Testcharmvision.GetRunResponse.UiTars
    | Testcharmvision.GetRunResponse.WorkflowRun;

export namespace GetRunResponse {
    export interface TaskV1 extends Testcharmvision.TaskRunResponse {
        run_type: "task_v1";
    }

    export interface TaskV2 extends Testcharmvision.TaskRunResponse {
        run_type: "task_v2";
    }

    export interface OpenaiCua extends Testcharmvision.TaskRunResponse {
        run_type: "openai_cua";
    }

    export interface AnthropicCua extends Testcharmvision.TaskRunResponse {
        run_type: "anthropic_cua";
    }

    export interface UiTars extends Testcharmvision.TaskRunResponse {
        run_type: "ui_tars";
    }

    export interface WorkflowRun extends Testcharmvision.WorkflowRunResponse {
        run_type: "workflow_run";
    }
}
