// This file was auto-generated by Fern from our API Definition.

/**
 * Prompt action parameters.
 */
export interface PromptAction {
    /** The prompt to send to the LLM */
    prompt: string;
    /** Optional JSON schema to structure the response */
    response_schema?: Record<string, unknown>;
    /** Optional model configuration */
    model?: Record<string, unknown>;
}
