// This file was auto-generated by Fern from our API Definition.

export const TestcharmvisionSchemasRunBlocksCredentialType = {
    Testcharmvision: "testcharmvision",
    Bitwarden: "bitwarden",
    OnePassword: "1password",
    AzureVault: "azure_vault",
} as const;
export type TestcharmvisionSchemasRunBlocksCredentialType =
    (typeof TestcharmvisionSchemasRunBlocksCredentialType)[keyof typeof TestcharmvisionSchemasRunBlocksCredentialType];
