// This file was auto-generated by Fern from our API Definition.

import type * as Testcharmvision from "../index.js";

export type UrlBlockParametersItem =
    | Testcharmvision.UrlBlockParametersItem.AwsSecret
    | Testcharmvision.UrlBlockParametersItem.AzureSecret
    | Testcharmvision.UrlBlockParametersItem.AzureVaultCredential
    | Testcharmvision.UrlBlockParametersItem.BitwardenCreditCardData
    | Testcharmvision.UrlBlockParametersItem.BitwardenLoginCredential
    | Testcharmvision.UrlBlockParametersItem.BitwardenSensitiveInformation
    | Testcharmvision.UrlBlockParametersItem.Context
    | Testcharmvision.UrlBlockParametersItem.Credential
    | Testcharmvision.UrlBlockParametersItem.Onepassword
    | Testcharmvision.UrlBlockParametersItem.Output
    | Testcharmvision.UrlBlockParametersItem.Workflow;

export namespace UrlBlockParametersItem {
    export interface AwsSecret extends Testcharmvision.AwsSecretParameter {
        parameter_type: "aws_secret";
    }

    export interface AzureSecret extends Testcharmvision.AzureSecretParameter {
        parameter_type: "azure_secret";
    }

    export interface AzureVaultCredential extends Testcharmvision.AzureVaultCredentialParameter {
        parameter_type: "azure_vault_credential";
    }

    export interface BitwardenCreditCardData extends Testcharmvision.BitwardenCreditCardDataParameter {
        parameter_type: "bitwarden_credit_card_data";
    }

    export interface BitwardenLoginCredential extends Testcharmvision.BitwardenLoginCredentialParameter {
        parameter_type: "bitwarden_login_credential";
    }

    export interface BitwardenSensitiveInformation extends Testcharmvision.BitwardenSensitiveInformationParameter {
        parameter_type: "bitwarden_sensitive_information";
    }

    export interface Context extends Testcharmvision.ContextParameter {
        parameter_type: "context";
    }

    export interface Credential extends Testcharmvision.CredentialParameter {
        parameter_type: "credential";
    }

    export interface Onepassword extends Testcharmvision.OnePasswordCredentialParameter {
        parameter_type: "onepassword";
    }

    export interface Output extends Testcharmvision.OutputParameter {
        parameter_type: "output";
    }

    export interface Workflow extends Testcharmvision.WorkflowParameter {
        parameter_type: "workflow";
    }
}
