// This file was auto-generated by Fern from our API Definition.

export const WorkflowParameterType = {
    String: "string",
    Integer: "integer",
    Float: "float",
    Boolean: "boolean",
    Json: "json",
    FileUrl: "file_url",
    CredentialId: "credential_id",
} as const;
export type WorkflowParameterType = (typeof WorkflowParameterType)[keyof typeof WorkflowParameterType];
