// This file was auto-generated by Fern from our API Definition.

import type * as Testcharmvision from "../index.js";

export interface Workflow {
    workflow_id: string;
    organization_id: string;
    title: string;
    workflow_permanent_id: string;
    version: number;
    is_saved_task: boolean;
    is_template?: boolean;
    description?: string;
    workflow_definition: Testcharmvision.WorkflowDefinition;
    proxy_location?: Workflow.ProxyLocation;
    webhook_callback_url?: string;
    totp_verification_url?: string;
    totp_identifier?: string;
    persist_browser_session?: boolean;
    model?: Record<string, unknown>;
    status?: Testcharmvision.WorkflowStatus;
    max_screenshot_scrolls?: number;
    extra_http_headers?: Record<string, string | undefined>;
    run_with?: string;
    ai_fallback?: boolean;
    cache_key?: string;
    run_sequentially?: boolean;
    sequential_key?: string;
    folder_id?: string;
    import_error?: string;
    created_at: string;
    modified_at: string;
    deleted_at?: string;
}

export namespace Workflow {
    export type ProxyLocation = Testcharmvision.ProxyLocation | Testcharmvision.GeoTarget | Record<string, unknown>;
}
