servers: 
  - url: https://api.skyvern.com
    x-fern-server-name: Production

paths:
  /api/v1/webhook:
    post:
      x-fern-sdk-group-name:
        - server
      x-fern-sdk-method-name: webhook
  /api/v1/heartbeat:
    get:
      x-fern-sdk-group-name:
        - server
      x-fern-sdk-method-name: checkStatus
  /api/v1/tasks:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getTasks
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: createTask
  /api/v1/tasks/{task_id}/steps:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getTaskSteps
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: executeTaskSteps
  /api/v1/tasks/{task_id}/steps/{step_id}:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: executeTaskStep
  /api/v1/tasks/{task_id}:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getTask
  /api/v1/tasks/{task_id}/cancel:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: cancelTask
  /api/v1/workflows/runs/{workflow_run_id}/cancel:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: cancelWorkflowRun
  /api/v1/tasks/{task_id}/retry_webhook:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: retryWebhook
  /api/v1/internal/tasks/{task_id}:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getTaskInternal
  /api/v1/internal/tasks:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getTasksInternal
  /api/v1/{entity_type}/{entity_id}/artifacts:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEntityArtifacts
  /api/v1/tasks/{task_id}/steps/{step_id}/artifacts:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getTaskStepArtifacts
  /api/v1/tasks/{task_id}/actions:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getTaskActions
  /api/v1/workflows/{workflow_id}/run:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: executeWorkflow
  /api/v1/workflows/runs:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getWorkflowRuns
  /api/v1/workflows/{workflow_permanent_id}/runs:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getWorkflowRunsForWorkflowPermanentId
  /api/v1/workflows/{workflow_id}/runs/{workflow_run_id}:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getWorkflowRun
  /api/v1/workflows/{workflow_id}/runs/{workflow_run_id}/timeline:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getWorkflowRunTimeline
  /api/v1/workflows/runs/{workflow_run_id}:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getWorkflowRunByRunId
  /api/v1/workflows:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getWorkflows
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: createWorkflow
  /api/v1/workflows/{workflow_permanent_id}:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getWorkflow
    put:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: updateWorkflow
    delete:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: deleteWorkflow
  /api/v1/workflows/:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: listWorkflows
  /api/v1/workflows/{workflow_permanent_id}/:
    get:
      x-fern-ignore: true
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getWorkflowByPermanentId
  /api/v1/suggest/{ai_suggestion_type}/:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: makeAiSuggestion
  /api/v1/generate/task/:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: generateTask
  /api/v1/organizations:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getOrganizations
    put:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: updateOrganization
  /api/v1/organizations/{organization_id}/apikeys:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getOrgApiKeys
  /api/v1/upload_file:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: uploadFile
  /api/v1/browser_sessions/{browser_session_id}:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getBrowserSessionById
  /api/v1/browser_sessions:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getBrowserSessions
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: createBrowserSession
  /api/v1/browser_sessions/close:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: closeBrowserSessions
  /api/v1/browser_sessions/{session_id}/close:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: closeBrowserSession
  /api/v2/tasks:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: observerTaskV2
  /api/v2/tasks/{task_id}:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getObserverTaskV2
  /api/v1/totp:
    post:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: saveTotpCode
  /api/v1/eval/workflows/runs:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalWorkflowRuns
  /api/v1/eval/workflows/{workflow_id}/runs/{workflow_run_id}:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalWorkflowRun
  /api/v1/eval/workflows/{workflow_id}/runs/{workflow_run_id}/timeline/:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalWorkflowRunTimeline
  /api/v1/eval/workflows/{workflow_id}/runs/{workflow_run_id}/timeline:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: listWorkflowRunTimeline
  /api/v1/eval/workflows/runs/{workflow_run_id}:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalWorkflowRunByRunId
  /api/v1/eval/workflows/{workflow_permanent_id}/:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalWorkflow
  /api/v1/eval/workflows/{workflow_permanent_id}:
    get:
      x-fern-ignore: true
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalWorkflowByPermanentId
  /api/v1/eval/workflows/{workflow_permanent_id}/runs:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalWorkflowRunsForWorkflowPermanentId
  /api/v1/eval/{entity_type}/{entity_id}/artifacts:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalEntityArtifacts
  /api/v1/eval/tasks/{task_id}/actions:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalTaskActions
  /api/v1/eval/tasks/{task_id}/steps/{step_id}/artifacts:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalTaskStepArtifacts
  /api/v1/eval/tasks/{task_id}/steps:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getEvalTaskSteps
  /api/v1/eval/tasks:
    get:
      x-fern-sdk-group-name:
        - agent
      x-fern-sdk-method-name: getAgentTasks
