// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../../../../index.js";

/**
 * @example
 *     {
 *         page: 1,
 *         page_size: 1,
 *         status: "active",
 *         search: "search"
 *     }
 */
export interface SchedulesListAllRequest {
    page?: number;
    page_size?: number;
    /** Filter by status: 'active' or 'paused' */
    status?: Skyvern.SchedulesListAllRequestStatus;
    /** Search by workflow title or schedule name */
    search?: string;
}
