# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class InputOrSelectContext(UniversalBaseModel):
    intention: typing.Optional[str] = None
    field: typing.Optional[str] = None
    is_required: typing.Optional[bool] = None
    is_search_bar: typing.Optional[bool] = None
    is_location_input: typing.Optional[bool] = None
    is_date_related: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
