# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RunWebhookReplayResponse(UniversalBaseModel):
    run_id: str = pydantic.Field()
    """
    Identifier of the run that was replayed
    """

    run_type: str = pydantic.Field()
    """
    Run type associated with the payload
    """

    default_webhook_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Webhook URL stored on the original run configuration
    """

    target_webhook_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Webhook URL that the replay attempted to reach
    """

    payload: str = pydantic.Field()
    """
    JSON payload that was delivered during the replay attempt
    """

    headers: typing.Dict[str, str] = pydantic.Field()
    """
    Signed headers that were generated for the replay attempt
    """

    status_code: typing.Optional[int] = pydantic.Field(default=None)
    """
    HTTP status code returned by the webhook receiver, if available
    """

    latency_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    Round-trip latency in milliseconds for the replay attempt
    """

    response_body: typing.Optional[str] = pydantic.Field(default=None)
    """
    Body returned by the webhook receiver (truncated to 2KB)
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if the replay attempt failed
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
