# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TagValueRenameResponse(UniversalBaseModel):
    """
    Response for ``PATCH /v1/tag-values/{key}/rename``: the renamed label with its
    carried-over color and the number of workflows re-tagged.
    """

    key: str
    value: str
    color: str
    renamed_workflow_count: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
