# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tag_delete_input import TagDeleteInput
from .tag_input import TagInput


class TagApplyRequest(UniversalBaseModel):
    """
    Body for ``POST /v1/workflows/{wpid}/tags``. Either field may be empty (both
    empty is a no-op). On a same-identity collision, set wins over delete.
    """

    tags: typing.Optional[typing.List[TagInput]] = pydantic.Field(default=None)
    """
    Tags to set (overwrite). List of {key?, value} objects.
    """

    tags_to_delete: typing.Optional[typing.List[TagDeleteInput]] = pydantic.Field(default=None)
    """
    Tags to soft-delete. List of {key?, value?} targets.
    """

    colors: typing.Optional[typing.Dict[str, typing.Optional[str]]] = pydantic.Field(default=None)
    """
    Optional map of grouped tag key to palette color name for the value being set. Keys absent from this map keep their existing color or receive a random palette color.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
