# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TagInput(UniversalBaseModel):
    """
    One tag to set. ``value`` is the required label; ``key`` is the optional
    group — null for a standalone label, set for a grouped label (e.g. env:prod).
    """

    key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional group (key). Omit for a standalone label.
    """

    value: str = pydantic.Field()
    """
    Label (value). Always required.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
