# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tag_response import TagResponse


class TagsResponse(UniversalBaseModel):
    """
    Current tags for a workflow. A list (not a key-map) so standalone labels,
    which have no key, are representable.
    """

    workflow_permanent_id: str
    tags: typing.List[TagResponse]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
