# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TaskRunListItem(UniversalBaseModel):
    """
    Lightweight run-history item backed by the task_runs table.
    """

    task_run_id: str
    run_id: str
    task_run_type: str
    status: str
    title: typing.Optional[str] = None
    started_at: typing.Optional[dt.datetime] = None
    finished_at: typing.Optional[dt.datetime] = None
    created_at: dt.datetime
    workflow_permanent_id: typing.Optional[str] = None
    script_run: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
