# This file was auto-generated by Fern from our API Definition.

import typing

TaskV2Status = typing.Union[
    typing.Literal["created", "queued", "running", "failed", "terminated", "canceled", "timed_out", "completed"],
    typing.Any,
]
