# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .workflow_definition import WorkflowDefinition
from .workflow_proxy_location import WorkflowProxyLocation
from .workflow_status import WorkflowStatus


class Workflow(UniversalBaseModel):
    workflow_id: str
    organization_id: str
    title: str
    workflow_permanent_id: str
    version: int
    is_saved_task: bool
    is_template: typing.Optional[bool] = None
    description: typing.Optional[str] = None
    workflow_definition: WorkflowDefinition
    proxy_location: typing.Optional[WorkflowProxyLocation] = None
    webhook_callback_url: typing.Optional[str] = None
    totp_verification_url: typing.Optional[str] = None
    totp_identifier: typing.Optional[str] = None
    persist_browser_session: typing.Optional[bool] = None
    pin_saved_session_ip: typing.Optional[bool] = None
    browser_profile_id: typing.Optional[str] = None
    model: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    status: typing.Optional[WorkflowStatus] = None
    max_screenshot_scrolls: typing.Optional[int] = None
    max_elapsed_time_minutes: typing.Optional[int] = None
    extra_http_headers: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None
    cdp_connect_headers: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None
    run_with: typing.Optional[str] = None
    ai_fallback: typing.Optional[bool] = None
    cache_key: typing.Optional[str] = None
    adaptive_caching: typing.Optional[bool] = None
    code_version: typing.Optional[int] = None
    generate_script_on_terminal: typing.Optional[bool] = None
    run_sequentially: typing.Optional[bool] = None
    sequential_key: typing.Optional[str] = None
    folder_id: typing.Optional[str] = None
    import_error: typing.Optional[str] = None
    created_by: typing.Optional[str] = None
    edited_by: typing.Optional[str] = None
    created_at: dt.datetime
    modified_at: dt.datetime
    deleted_at: typing.Optional[dt.datetime] = None
    agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Alias of `workflow_permanent_id` — the stable agent identifier (starts with `wpid_`).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .context_parameter import ContextParameter  # noqa: E402, F401, I001
from .for_loop_block import ForLoopBlock  # noqa: E402, F401, I001
from .while_loop_block import WhileLoopBlock  # noqa: E402, F401, I001

update_forward_refs(Workflow)
