# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WorkflowScheduleUpsertRequest(UniversalBaseModel):
    cron_expression: typing.Optional[str] = None
    interval_seconds: typing.Optional[int] = None
    first_fire_at: typing.Optional[dt.datetime] = None
    timezone: str
    enabled: typing.Optional[bool] = None
    parameters: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
