# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workflow_run_request_output_proxy_location import WorkflowRunRequestOutputProxyLocation


class WorkflowRunRequestOutput(UniversalBaseModel):
    workflow_id: str = pydantic.Field()
    """
    ID of the workflow to run. Workflow ID starts with `wpid_`.
    """

    parameters: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Parameters to pass to the workflow
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    The title for this workflow run
    """

    proxy_location: typing.Optional[WorkflowRunRequestOutputProxyLocation] = pydantic.Field(default=None)
    """
    
    Geographic Proxy location to route the browser traffic through. This is only available in Skyvern Cloud.
    
    Available geotargeting options:
    - RESIDENTIAL: the default value. Skyvern Cloud uses a random US residential proxy.
    - RESIDENTIAL_ES: Spain
    - RESIDENTIAL_IE: Ireland
    - RESIDENTIAL_GB: United Kingdom
    - RESIDENTIAL_IN: India
    - RESIDENTIAL_JP: Japan
    - RESIDENTIAL_FR: France
    - RESIDENTIAL_DE: Germany
    - RESIDENTIAL_NZ: New Zealand
    - RESIDENTIAL_PH: Philippines
    - RESIDENTIAL_KR: South Korea
    - RESIDENTIAL_SA: Saudi Arabia
    - RESIDENTIAL_ZA: South Africa
    - RESIDENTIAL_AR: Argentina
    - RESIDENTIAL_AU: Australia
    - RESIDENTIAL_BR: Brazil
    - RESIDENTIAL_TR: Turkey
    - RESIDENTIAL_CA: Canada
    - RESIDENTIAL_MX: Mexico
    - RESIDENTIAL_IT: Italy
    - RESIDENTIAL_NL: Netherlands
    - RESIDENTIAL_ISP: ISP proxy
    - US-CA: California (deprecated, routes through RESIDENTIAL_ISP)
    - US-NY: New York (deprecated, routes through RESIDENTIAL_ISP)
    - US-TX: Texas (deprecated, routes through RESIDENTIAL_ISP)
    - US-FL: Florida (deprecated, routes through RESIDENTIAL_ISP)
    - US-WA: Washington (deprecated, routes through RESIDENTIAL_ISP)
    - NONE: No proxy
    
    For self-hosted deployments, you can pass a custom proxy URL as a dict: {"url": "http://user:password@proxy.example.com:8080"}. This routes the browser through your own proxy server and takes precedence over any globally configured proxy pool.
     Can also be a GeoTarget object for granular city/state targeting: {"country": "US", "subdivision": "CA", "city": "San Francisco"}
    """

    webhook_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL to send workflow status updates to after a run is finished. Refer to https://www.skyvern.com/docs/running-tasks/webhooks-faq for webhook questions.
    """

    totp_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    
    URL that serves TOTP/2FA/MFA codes for Skyvern to use during the workflow run. Refer to https://www.skyvern.com/docs/credentials/totp#option-2-get-code-from-your-endpoint for more details.
    """

    totp_identifier: typing.Optional[str] = pydantic.Field(default=None)
    """
    
    Identifier for the TOTP/2FA/MFA code when the code is pushed to Skyvern. Refer to https://www.skyvern.com/docs/credentials/totp#option-3-push-code-to-skyvern for more details.
    """

    browser_session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of a Skyvern browser session to reuse, having it continue from the current screen state
    """

    browser_profile_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of a browser profile to reuse for this workflow run
    """

    max_screenshot_scrolls: typing.Optional[int] = pydantic.Field(default=None)
    """
    The maximum number of scrolls for the post action screenshot. When it's None or 0, it takes the current viewpoint screenshot.
    """

    max_elapsed_time_minutes: typing.Optional[int] = pydantic.Field(default=None)
    """
    Timeout this workflow run after the configured elapsed runtime in minutes. Maximum runtime is 4 hours.
    """

    extra_http_headers: typing.Optional[typing.Dict[str, typing.Optional[str]]] = pydantic.Field(default=None)
    """
    The extra HTTP headers for the requests in browser.
    """

    cdp_connect_headers: typing.Optional[typing.Dict[str, typing.Optional[str]]] = pydantic.Field(default=None)
    """
    HTTP headers attached ONLY to the CDP WebSocket handshake when connecting to a remote browser via browser_address. Use this for browser-provider auth (e.g., x-api-key for Skyvern Cloud, Browserless, or similar). These headers are NEVER forwarded to target websites.
    """

    browser_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    The CDP address for the workflow run.
    """

    ai_fallback: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to fallback to AI if the workflow run fails.
    """

    run_with: typing.Optional[str] = pydantic.Field(default=None)
    """
    Whether to run the workflow with agent or code. Null inherits from the workflow setting.
    """

    run_metadata: typing.Optional[typing.Dict[str, typing.Optional[str]]] = pydantic.Field(default=None)
    """
    String key/value metadata to attach to this workflow run for analytics tag filtering.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
