# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tag_item import TagItem


class WorkflowTagsBatchResponse(UniversalBaseModel):
    """
    Response for the batch endpoint.

    Workflows with no tags are present with an empty list so the frontend can
    distinguish "fetched, none set" from "not fetched" without a second call.
    Workflows outside the caller's org are silently absent (no leakage).
    """

    workflow_tags: typing.Dict[str, typing.List[TagItem]]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
