// This file was auto-generated by Fern from our API Definition.

import type * as Testcharmvision from "../../index.js";

/**
 * @example
 *     {
 *         folder_id: "folder_id",
 *         body: {}
 *     }
 */
export interface CreateWorkflowRequest {
    /** Optional folder ID to assign the workflow to */
    folder_id?: string;
    body: Testcharmvision.WorkflowRequest;
}
