// This file was auto-generated by Fern from our API Definition.

import type * as Testcharmvision from "../../index.js";

/**
 * @example
 *     {}
 */
export interface GetRunArtifactsRequest {
    artifact_type?: Testcharmvision.ArtifactType | Testcharmvision.ArtifactType[];
}
