apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: skyvern
type: Opaque
stringData:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_USER: skyvern
  POSTGRES_PASSWORD: skyvern
  POSTGRES_DB: skyvern
