apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: skyvern
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_USER: skyvern
  POSTGRES_PASSWORD: skyvern
  POSTGRES_DB: skyvern