// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         include_deleted: true
 *     }
 */
export interface ListBrowserProfilesV1BrowserProfilesGetRequest {
    /** Include deleted browser profiles */
    include_deleted?: boolean;
}
