"""create azure_vault_credential_parameters table

Revision ID: 56f8e5de3703
Revises: 8de03b8cb83a
Create Date: 2025-09-09 02:47:48.751901+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f8e5de3703'
down_revision: Union[str, None] = '8de03b8cb83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azure_vault_credential_parameters',
    sa.Column('azure_vault_credential_parameter_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('login_id', sa.String(), nullable=False),
    sa.Column('password_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('azure_vault_credential_parameter_id')
    )
    op.create_index(op.f('ix_azure_vault_credential_parameters_workflow_id'), 'azure_vault_credential_parameters', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_azure_vault_credential_parameters_workflow_id'), table_name='azure_vault_credential_parameters')
    op.drop_table('azure_vault_credential_parameters')
    # ### end Alembic commands ###
