"""Rename use_cache field to generate_script in workflows table

Revision ID: rename_use_cache_to_generate_script
Revises: a027553be970
Create Date: 2025-08-10 03:38:00.000000+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "rename_use_cache_to_generate_script"
down_revision: Union[str, None] = "a027553be970"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new generate_script column with same properties as use_cache
    op.add_column("workflows", sa.Column("generate_script", sa.Boolean(), nullable=False, server_default=sa.false()))
    
    # Copy data from use_cache to generate_script
    op.execute("UPDATE workflows SET generate_script = use_cache")
    
    # Remove server default after data migration
    op.alter_column("workflows", "generate_script", server_default=None)
    
    # Drop the old use_cache column
    op.drop_column("workflows", "use_cache")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back use_cache column
    op.add_column("workflows", sa.Column("use_cache", sa.Boolean(), nullable=False, server_default=sa.false()))
    
    # Copy data from generate_script back to use_cache
    op.execute("UPDATE workflows SET use_cache = generate_script")
    
    # Remove server default after data migration
    op.alter_column("workflows", "use_cache", server_default=None)
    
    # Drop the new generate_script column
    op.drop_column("workflows", "generate_script")
    # ### end Alembic commands ###