"""add http request block columns to workflow_run_blocks

Revision ID: 6cf2c1e15039
Revises: afeed80576cb
Create Date: 2025-06-27 02:11:36.372859+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cf2c1e15039'
down_revision: Union[str, None] = 'afeed80576cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_run_blocks', sa.Column('method', sa.String(length=10), nullable=True))
    op.add_column('workflow_run_blocks', sa.Column('url', sa.String(), nullable=True))
    op.add_column('workflow_run_blocks', sa.Column('headers', sa.JSON(), nullable=True))
    op.add_column('workflow_run_blocks', sa.Column('timeout', sa.Integer(), nullable=True))
    op.add_column('workflow_run_blocks', sa.Column('follow_redirects', sa.Boolean(), nullable=True))
    op.alter_column('workflow_run_blocks', 'body',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='body::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_run_blocks', 'body',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('workflow_run_blocks', 'follow_redirects')
    op.drop_column('workflow_run_blocks', 'timeout')
    op.drop_column('workflow_run_blocks', 'headers')
    op.drop_column('workflow_run_blocks', 'url')
    op.drop_column('workflow_run_blocks', 'method')
    # ### end Alembic commands ###
