"""checksum in artifacts; workflow_system_prompt

Revision ID: 70b5f11e3655
Revises: d1474f2d1581
Create Date: 2026-04-25 21:40:15.008563+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70b5f11e3655"
down_revision: Union[str, None] = "d1474f2d1581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artifacts", sa.Column("checksum", sa.String(), nullable=True))
    op.add_column("observer_cruises", sa.Column("workflow_system_prompt", sa.UnicodeText(), nullable=True))
    op.add_column("tasks", sa.Column("workflow_system_prompt", sa.UnicodeText(), nullable=True))
    op.add_column(
        "workflow_runs",
        sa.Column(
            "ignore_inherited_workflow_system_prompt", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_runs", "ignore_inherited_workflow_system_prompt")
    op.drop_column("tasks", "workflow_system_prompt")
    op.drop_column("observer_cruises", "workflow_system_prompt")
    op.drop_column("artifacts", "checksum")
    # ### end Alembic commands ###
