import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import { useCredentialsQuery } from "@/routes/workflows/hooks/useCredentialsQuery";
import CloudContext from "@/store/CloudContext";
import { useContext, useEffect, useMemo, useState } from "react";
import { useWorkflowHasChangesStore } from "@/store/WorkflowHasChangesStore";
import { useWorkflowParametersStore } from "@/store/WorkflowParametersStore";
import { CredentialsModal } from "@/routes/credentials/CredentialsModal";
import {
  CheckIcon,
  ChevronDownIcon,
  Cross2Icon,
  ExclamationTriangleIcon,
  PlusIcon,
  ReloadIcon,
} from "@radix-ui/react-icons";
import { getHostname } from "@/util/getHostname";
import {
  CredentialModalTypes,
  useCredentialModalState,
} from "@/routes/credentials/useCredentialModalState";
import { useNodes, useReactFlow } from "@xyflow/react";
import { AppNode } from "..";
import { isLoginNode } from "./types";
import {
  isStartNode,
  isWorkflowStartNodeData,
  type WorkflowStartNodeData,
} from "../StartNode/types";
import {
  parameterIsSkyvernCredential,
  parameterIsBitwardenCredential,
  parameterIsOnePasswordCredential,
  parameterIsAzureVaultCredential,
  isAutoGeneratedCredentialKey,
  computeWrappedCredentialIds,
} from "../../types";
import { cn } from "@/util/utils";

const ROTATION_SELECTION_STRATEGY = "round_robin" as const;

type Props = {
  nodeId: string;
  value?: string;
  onChange?: (value: string) => void;
  editable?: boolean;
  /** Called when a credential with a tested_url is selected to auto-fill the login block URL */
  onUrlAutoFill?: (url: string) => void;
  /** Current URL value of the login block — skip auto-fill if already set */
  currentUrl?: string;
};

// Function to generate a unique credential parameter key
function generateDefaultCredentialParameterKey(existingKeys: string[]): string {
  const baseName = "credentials";

  // Check if "credentials" is available
  if (!existingKeys.includes(baseName)) {
    return baseName;
  }

  // Find the next available number
  let counter = 1;
  while (existingKeys.includes(`${baseName}_${counter}`)) {
    counter++;
  }

  return `${baseName}_${counter}`;
}

function LoginBlockCredentialSelector({
  nodeId,
  value,
  onChange,
  editable = true,
  onUrlAutoFill,
  currentUrl,
}: Props) {
  const { setIsOpen, setType } = useCredentialModalState();
  const nodes = useNodes<AppNode>();
  const { updateNodeData } = useReactFlow<AppNode>();
  const [rotationDraft, setRotationDraft] = useState(false);
  const {
    parameters: workflowParameters,
    setParameters: setWorkflowParameters,
  } = useWorkflowParametersStore();
  const setHasChanges = useWorkflowHasChangesStore(
    (state) => state.setHasChanges,
  );
  const credentialParameters = workflowParameters.filter(
    (parameter) =>
      parameter.parameterType === "credential" ||
      parameter.parameterType === "onepassword",
  );
  const isCloud = useContext(CloudContext);
  const { data: credentials = [], isLoading } = useCredentialsQuery({
    enabled: isCloud,
    page_size: 100,
  });

  // Get the set of credential IDs that are in the vault
  const credentialIdsInVault = useMemo(
    () => new Set(credentials.map((c) => c.credential_id)),
    [credentials],
  );

  const selectedSkyvernCredentialParameter = useMemo(() => {
    if (!value) return undefined;
    const parameter = credentialParameters.find((p) => p.key === value);
    if (!parameter || !parameterIsSkyvernCredential(parameter)) {
      return undefined;
    }
    return parameter;
  }, [value, credentialParameters]);

  useEffect(() => {
    setRotationDraft(false);
  }, [value]);

  // Determine which credential is currently selected (by credential_id)
  // This handles multiple cases:
  // 1. Skyvern credential parameters (have credentialId)
  // 2. Workflow inputs with credential_id type and default value
  const selectedCredentialId = useMemo(() => {
    if (!value) return undefined;

    // Check if it's a credential parameter
    const credentialParam = credentialParameters.find((p) => p.key === value);
    if (credentialParam && parameterIsSkyvernCredential(credentialParam)) {
      return credentialParam.credentialId;
    }

    // Check if it's a workflow input with credential_id type and default value
    const workflowParam = workflowParameters.find(
      (p) =>
        p.parameterType === "workflow" &&
        p.key === value &&
        p.dataType === "credential_id" &&
        typeof p.defaultValue === "string" &&
        p.defaultValue,
    );
    if (workflowParam && workflowParam.parameterType === "workflow") {
      return workflowParam.defaultValue as string;
    }

    return undefined;
  }, [value, credentialParameters, workflowParameters]);

  const rotationCredentialIds = useMemo(() => {
    const sourceIds = selectedSkyvernCredentialParameter?.credentialIds?.length
      ? selectedSkyvernCredentialParameter.credentialIds
      : selectedCredentialId
        ? [selectedCredentialId]
        : [];

    return sourceIds.filter((id, index, ids): id is string => {
      return typeof id === "string" && ids.indexOf(id) === index;
    });
  }, [selectedSkyvernCredentialParameter, selectedCredentialId]);

  const rotationIsSaved = rotationCredentialIds.length > 1;
  const rotationMode =
    Boolean(selectedSkyvernCredentialParameter) &&
    (rotationDraft || rotationIsSaved);

  const workflowStartNode = useMemo<
    { id: string; data: WorkflowStartNodeData } | undefined
  >(() => {
    const node = nodes.find(isStartNode);
    if (!node || !isWorkflowStartNodeData(node.data)) {
      return undefined;
    }
    return { id: node.id, data: node.data };
  }, [nodes]);

  // Check if the selected credential is missing (deleted)
  const isCredentialMissing = useMemo(() => {
    if (!selectedCredentialId) return false;
    return !credentialIdsInVault.has(selectedCredentialId);
  }, [selectedCredentialId, credentialIdsInVault]);

  // User-authored credential variables (custom-key Skyvern params, or workflow
  // credential_id params) surface their variable name; auto-generated keys keep
  // the plain credential-name render.
  const selectedCredentialVariable = useMemo(() => {
    if (!value || !selectedCredentialId) return undefined;

    const param = workflowParameters.find((p) => p.key === value);
    if (!param) return undefined;

    const isUserAuthored =
      (param.parameterType === "credential" &&
        parameterIsSkyvernCredential(param) &&
        !isAutoGeneratedCredentialKey(param.key)) ||
      (param.parameterType === "workflow" &&
        param.dataType === "credential_id");
    if (!isUserAuthored) return undefined;

    const credentialName = credentials.find(
      (c) => c.credential_id === selectedCredentialId,
    )?.name;
    if (!credentialName || credentialName === param.key) return undefined;
    return { key: param.key, credentialName };
  }, [value, selectedCredentialId, workflowParameters, credentials]);

  const wrappedCredentialIds = useMemo(
    () => computeWrappedCredentialIds(credentialParameters),
    [credentialParameters],
  );

  if (isCloud && isLoading) {
    return <Skeleton className="h-8 w-full" />;
  }

  const allCredentialOptions = credentials.map((credential) => ({
    label: credential.name,
    value: credential.credential_id,
    type: "credential" as const,
    hasBrowserProfile: !!credential.browser_profile_id,
    browserProfileUrl: credential.tested_url ?? null,
  }));

  const credentialOptions = allCredentialOptions.filter(
    (credential) => !wrappedCredentialIds.has(credential.value),
  );

  const selectedRotationCredentials = rotationCredentialIds.map(
    (credentialId) => {
      const option = allCredentialOptions.find(
        (credential) => credential.value === credentialId,
      );
      return {
        label: option?.label ?? credentialId,
        value: credentialId,
        hasBrowserProfile: option?.hasBrowserProfile ?? false,
      };
    },
  );

  // Auto-generated Skyvern wrappers are hidden (they back a direct credential
  // pick); user-authored Skyvern params and external vault params are listed.
  // Workflow credential_id params are authored in the Parameters panel, not here.
  const credentialParameterOptions = credentialParameters
    .filter((parameter) => {
      if (
        parameterIsSkyvernCredential(parameter) &&
        isAutoGeneratedCredentialKey(parameter.key)
      ) {
        return false;
      }
      return (
        parameterIsSkyvernCredential(parameter) ||
        parameterIsBitwardenCredential(parameter) ||
        parameterIsOnePasswordCredential(parameter) ||
        parameterIsAzureVaultCredential(parameter)
      );
    })
    .map((parameter) => ({
      label: parameter.key,
      value: parameter.key,
      type: "parameter" as const,
    }));

  const options = [...credentialOptions, ...credentialParameterOptions];

  // When the active value is a param-key option (any user-authored param, incl.
  // wrapped Skyvern credentials), the controlled value must be the key — not the
  // resolved credentialId, whose row is filtered out of credentialOptions and so
  // has no matching SelectItem. Keep this independent of selectedCredentialVariable,
  // which is suppressed when key === credential name but still needs a valid value.
  const valueIsParameterOption = options.some(
    (option) => option.type === "parameter" && option.value === value,
  );

  // Always pass a defined string so Radix Select stays controlled; uncontrolled
  // mode caches the picked value and silently skips re-firing onValueChange.
  let selectValue: string;
  if (isCredentialMissing) {
    selectValue = "";
  } else if (valueIsParameterOption) {
    selectValue = value ?? "";
  } else {
    selectValue = selectedCredentialId ?? value ?? "";
  }

  const writeRotationCredentialIds = (credentialIds: Array<string>) => {
    if (!selectedSkyvernCredentialParameter || credentialIds.length === 0) {
      return;
    }

    const orderedCredentialIds = credentialIds.filter((id, index, ids) => {
      return ids.indexOf(id) === index;
    });
    const firstCredentialId = orderedCredentialIds[0];
    if (!firstCredentialId) {
      return;
    }

    const newParameters = workflowParameters.map((parameter) => {
      if (
        parameter.key !== selectedSkyvernCredentialParameter.key ||
        parameter.parameterType !== "credential" ||
        !parameterIsSkyvernCredential(parameter)
      ) {
        return parameter;
      }

      if (orderedCredentialIds.length < 2) {
        return {
          ...parameter,
          credentialId: firstCredentialId,
          credentialIds: null,
          selectionStrategy: null,
          dataType: undefined,
        };
      }

      return {
        ...parameter,
        credentialId: firstCredentialId,
        credentialIds: orderedCredentialIds,
        selectionStrategy: ROTATION_SELECTION_STRATEGY,
        dataType: undefined,
      };
    });

    setWorkflowParameters(newParameters);
    setHasChanges(true);
  };

  const toggleRotationCredential = (credentialId: string) => {
    if (!editable) return;
    const nextCredentialIds = rotationCredentialIds.includes(credentialId)
      ? rotationCredentialIds.filter((id) => id !== credentialId)
      : [...rotationCredentialIds, credentialId];

    if (nextCredentialIds.length === 0) {
      return;
    }

    writeRotationCredentialIds(nextCredentialIds);
    if (nextCredentialIds.length < 2) {
      setRotationDraft(false);
    }
  };

  const disableRotation = () => {
    if (!editable) return;
    if (rotationCredentialIds.length > 0) {
      writeRotationCredentialIds([rotationCredentialIds[0]!]);
    }
    setRotationDraft(false);
  };

  const setRunSequentially = (checked: boolean) => {
    if (!workflowStartNode) {
      return;
    }
    updateNodeData(workflowStartNode.id, {
      runSequentially: checked,
      sequentialKey: checked ? workflowStartNode.data.sequentialKey : null,
    });
    setHasChanges(true);
  };

  if (rotationMode) {
    return (
      <>
        <div className="space-y-2">
          <Popover>
            <PopoverTrigger asChild>
              <Button
                type="button"
                variant="outline"
                className="h-auto min-h-10 w-full justify-between px-3 py-2 text-left text-xs font-normal"
                disabled={!editable}
              >
                <span className="truncate">
                  {rotationCredentialIds.length > 1
                    ? `Rotates across ${rotationCredentialIds.length} credentials`
                    : "Add credentials to rotate"}
                </span>
                <ChevronDownIcon className="ml-2 size-4 shrink-0 text-muted-foreground" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-[28rem] p-0" align="start">
              <Command>
                <CommandInput placeholder="Search credentials..." />
                <CommandList>
                  <CommandEmpty>No credentials found.</CommandEmpty>
                  <CommandGroup>
                    {allCredentialOptions.map((option) => {
                      const isSelected = rotationCredentialIds.includes(
                        option.value,
                      );
                      return (
                        <CommandItem
                          key={option.value}
                          className="cursor-pointer"
                          onSelect={() =>
                            toggleRotationCredential(option.value)
                          }
                        >
                          <div
                            className={cn(
                              "mr-2 flex size-4 items-center justify-center rounded-sm border border-primary",
                              isSelected
                                ? "bg-primary text-primary-foreground"
                                : "opacity-50 [&_svg]:invisible",
                            )}
                          >
                            <CheckIcon className="size-4" />
                          </div>
                          <div className="flex min-w-0 items-center gap-2">
                            <span className="truncate">{option.label}</span>
                            {option.hasBrowserProfile ? (
                              <span className="rounded bg-green-900/40 px-1.5 py-0.5 text-[10px] text-green-400">
                                saved-profile
                              </span>
                            ) : null}
                            {option.browserProfileUrl ? (
                              <span className="truncate text-[10px] text-muted-foreground">
                                {getHostname(option.browserProfileUrl)}
                              </span>
                            ) : null}
                          </div>
                        </CommandItem>
                      );
                    })}
                  </CommandGroup>
                </CommandList>
              </Command>
            </PopoverContent>
          </Popover>

          <div className="space-y-1">
            {selectedRotationCredentials.map((credential, index) => (
              <div
                key={credential.value}
                className="flex items-center gap-2 rounded-md border border-slate-700/60 bg-slate-900/40 px-2 py-1.5"
              >
                <span className="flex size-5 shrink-0 items-center justify-center rounded bg-slate-800 text-[10px] text-slate-300">
                  {index + 1}
                </span>
                <span className="min-w-0 flex-1 truncate text-xs text-slate-200">
                  {credential.label}
                </span>
                {credential.hasBrowserProfile ? (
                  <span
                    className="shrink-0 rounded bg-slate-800 px-1.5 py-0.5 text-[10px] text-slate-400"
                    title="Has a saved browser profile - runs with this account keep its logged-in session"
                  >
                    Profile
                  </span>
                ) : null}
                <button
                  type="button"
                  className="text-slate-500 transition-colors hover:text-slate-200 disabled:pointer-events-none disabled:opacity-50"
                  disabled={!editable || selectedRotationCredentials.length < 2}
                  onClick={() => toggleRotationCredential(credential.value)}
                  aria-label={`Remove ${credential.label}`}
                >
                  <Cross2Icon className="size-3.5" />
                </button>
              </div>
            ))}
          </div>

          {rotationCredentialIds.length > 1 ? (
            <div className="flex items-start gap-2 text-xs text-slate-400">
              <div className="space-y-0.5">
                <span>Disable parallel runs</span>
                <p className="text-[11px] leading-4 text-slate-500">
                  Queues this workflow's runs one at a time so rotated accounts
                  never log in simultaneously.
                </p>
              </div>
              <Switch
                className="ml-auto shrink-0"
                checked={
                  workflowStartNode
                    ? workflowStartNode.data.runSequentially
                    : false
                }
                disabled={!editable || !workflowStartNode}
                onCheckedChange={setRunSequentially}
              />
            </div>
          ) : null}

          <button
            type="button"
            className="text-xs text-slate-400 transition-colors hover:text-slate-200 disabled:pointer-events-none disabled:opacity-50"
            disabled={!editable}
            onClick={disableRotation}
          >
            Use single credential
          </button>
        </div>
        <CredentialsModal
          onCredentialCreated={(id) => {
            if (!editable) return;
            const existingKeys = workflowParameters.map((param) => param.key);
            const newKey = generateDefaultCredentialParameterKey(existingKeys);

            setWorkflowParameters([
              ...workflowParameters,
              {
                parameterType: "credential",
                credentialId: id,
                key: newKey,
              },
            ]);
            setHasChanges(true);
            onChange?.(newKey);
          }}
        />
      </>
    );
  }

  return (
    <>
      <Select
        disabled={!editable}
        key={value ?? "no-credential"}
        value={selectValue}
        onValueChange={(newValue) => {
          if (!editable) return;
          if (newValue === "new") {
            setIsOpen(true);
            setType(CredentialModalTypes.PASSWORD);
            return;
          }

          let newParameters = [...workflowParameters];

          const loginNodes = nodes
            .filter((node) => node.id !== nodeId)
            .filter(isLoginNode);

          // Only auto-gen wrappers are garbage-collected on switch; user-authored
          // params are intentional named variables and must survive.
          const currentParameter = workflowParameters.find((parameter) => {
            if (parameter.parameterType !== "credential") return false;
            if (!parameterIsSkyvernCredential(parameter)) return false;
            if (!isAutoGeneratedCredentialKey(parameter.key)) return false;
            return parameter.key === value;
          });

          const isUsedInOtherLoginNodes =
            value &&
            loginNodes.some((node) => node.data.parameterKeys.includes(value));

          // Only delete old parameter if it's not used elsewhere
          const deleteOldParameter =
            currentParameter && !isUsedInOtherLoginNodes;

          if (deleteOldParameter) {
            newParameters = newParameters.filter(
              (parameter) => parameter.key !== value,
            );
          }

          // Check if user selected an actual credential (by credential_id)
          const selectedCredential = credentialOptions.find(
            (option) => option.value === newValue,
          );

          let parameterKeyToUse = newValue;

          if (selectedCredential) {
            // User selected an actual credential
            const existingParameter = newParameters.find((parameter) => {
              return (
                parameter.parameterType === "credential" &&
                parameterIsSkyvernCredential(parameter) &&
                parameter.credentialId === newValue &&
                (parameter.credentialIds?.length ?? 0) < 2
              );
            });

            if (existingParameter) {
              // Reuse the existing parameter
              parameterKeyToUse = existingParameter.key;
            } else {
              // Create a new parameter for this credential
              const existingKeys = newParameters.map((param) => param.key);
              const newKey =
                generateDefaultCredentialParameterKey(existingKeys);
              parameterKeyToUse = newKey;

              newParameters = [
                ...newParameters,
                {
                  parameterType: "credential",
                  credentialId: newValue,
                  key: newKey,
                },
              ];
            }
          }
          // If user selected a parameter (non-Skyvern credential or input)
          // just use it directly (parameterKeyToUse is already set to newValue)

          // Update Zustand store first, then call onChange
          // This ensures workflowParameters is updated before the parent re-renders
          // with the new value, so selectedCredentialId computes correctly
          setWorkflowParameters(newParameters);
          // Zustand mutation is invisible to the node-change listener, so the unsaved-changes blocker would miss this edit.
          setHasChanges(true);
          setRotationDraft(false);
          onChange?.(parameterKeyToUse);

          // Auto-fill the login block URL from the credential's tested_url
          // when the URL field is empty.
          if (
            selectedCredential &&
            !currentUrl?.trim() &&
            selectedCredential.browserProfileUrl
          ) {
            onUrlAutoFill?.(selectedCredential.browserProfileUrl);
          }
        }}
      >
        <SelectTrigger
          className={
            isCredentialMissing
              ? "h-auto min-h-10 w-full border-red-500 text-red-500"
              : "h-auto min-h-10 w-full"
          }
        >
          {isCredentialMissing ? (
            <div className="flex items-center gap-2 text-red-500">
              <ExclamationTriangleIcon className="size-4" />
              <span>Credential not found</span>
            </div>
          ) : selectedCredentialVariable ? (
            <div className="flex min-w-0 flex-col items-start text-left">
              <span className="truncate">{selectedCredentialVariable.key}</span>
              <span className="truncate text-xs text-muted-foreground">
                defaults to credential:{" "}
                {selectedCredentialVariable.credentialName}
              </span>
            </div>
          ) : (
            <SelectValue placeholder="Select a credential" />
          )}
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="new">
            <div className="flex items-center gap-2">
              <PlusIcon className="size-4" />
              <span>Add new credential</span>
            </div>
          </SelectItem>
          {options.length > 0 && <SelectSeparator />}
          {options.map((option) => (
            <SelectItem key={option.value} value={option.value}>
              <div className="flex items-center gap-2">
                <span>{option.label}</span>
                {"hasBrowserProfile" in option && option.hasBrowserProfile && (
                  <>
                    <span className="rounded bg-green-900/40 px-1.5 py-0.5 text-[10px] text-green-400">
                      saved-profile
                    </span>
                    {option.browserProfileUrl && (
                      <span className="text-[10px] text-muted-foreground">
                        {getHostname(option.browserProfileUrl)}
                      </span>
                    )}
                  </>
                )}
              </div>
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
      {!rotationMode &&
      selectedSkyvernCredentialParameter &&
      selectedCredentialId &&
      !isCredentialMissing ? (
        <button
          type="button"
          className="mt-2 inline-flex items-center gap-1 text-xs text-slate-400 transition-colors hover:text-slate-200 disabled:pointer-events-none disabled:opacity-50"
          disabled={!editable}
          onClick={() => setRotationDraft(true)}
        >
          <ReloadIcon className="size-3" />
          Rotate between multiple credentials
        </button>
      ) : null}
      <CredentialsModal
        onCredentialCreated={(id) => {
          if (!editable) return;
          const existingKeys = workflowParameters.map((param) => param.key);
          const newKey = generateDefaultCredentialParameterKey(existingKeys);

          // Update Zustand store first, then call onChange
          setWorkflowParameters([
            ...workflowParameters,
            {
              parameterType: "credential",
              credentialId: id,
              key: newKey,
            },
          ]);
          setHasChanges(true);
          onChange?.(newKey);
        }}
      />
    </>
  );
}

export { LoginBlockCredentialSelector };
