import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import { useCredentialsQuery } from "@/routes/workflows/hooks/useCredentialsQuery";
import { useSkyvernCredentialSourceAvailable } from "@/routes/workflows/hooks/useSkyvernCredentialSourceAvailable";
import { useEffect, useMemo, useState } from "react";
import { useWorkflowHasChangesStore } from "@/store/WorkflowHasChangesStore";
import { useWorkflowParametersStore } from "@/store/WorkflowParametersStore";
import { useWorkflowScopeReadOnly } from "../../WorkflowScopeContext";
import { CredentialsModal } from "@/routes/credentials/CredentialsModal";
import {
  CheckIcon,
  ChevronDownIcon,
  Cross2Icon,
  ExclamationTriangleIcon,
  PlusIcon,
  ReloadIcon,
} from "@radix-ui/react-icons";
import type { CredentialApiResponse } from "@/api/types";
import { getHostname } from "@/util/getHostname";
import { type CredentialFallbackTrigger } from "@/routes/workflows/types/workflowTypes";
import {
  CredentialModalTypes,
  useCredentialModalState,
} from "@/routes/credentials/useCredentialModalState";
import { useNodes, useReactFlow } from "@xyflow/react";
import { AppNode } from "..";
import { isLoginNode } from "./types";
import { useLoginGoalAutoFill } from "./useLoginGoalAutoFill";
import {
  isStartNode,
  isWorkflowStartNodeData,
  type WorkflowStartNodeData,
} from "../StartNode/types";
import {
  parameterIsSkyvernCredential,
  parameterIsBitwardenCredential,
  parameterIsOnePasswordCredential,
  parameterIsAzureVaultCredential,
  isAutoGeneratedCredentialKey,
  computeWrappedCredentialIds,
  type SkyvernCredential,
} from "../../types";
import { cn } from "@/util/utils";
import { keepPreviousData } from "@tanstack/react-query";
import { useDebounce } from "use-debounce";
import {
  isCredentialNotFoundError,
  useCredentialQuery,
} from "@/routes/workflows/hooks/useCredentialQuery";
import {
  CredentialCombobox,
  type CredentialComboboxSelection,
  type SelectedValueState,
} from "@/routes/workflows/components/CredentialCombobox";

const ROTATION_SELECTION_STRATEGY = "round_robin" as const;
const DEFAULT_FALLBACK_TRIGGER = "credential_failures" as const;

type Props = {
  nodeId: string;
  value?: string;
  onChange?: (value: string) => void;
  editable?: boolean;
  /** Called when a credential with a tested_url is selected to auto-fill the login block URL */
  onUrlAutoFill?: (url: string) => void;
  /** Current URL value of the login block — skip auto-fill if already set */
  currentUrl?: string;
  onInstructionsAutoFill?: (instructions: string) => void;
  /** Current login-goal value, checked against computeLoginGoalPrefill's guard */
  currentInstructions?: string;
};

type CredentialListRowProps = {
  credentialId: string;
  credential: CredentialApiResponse | undefined;
  index: number;
  editable: boolean;
  canRemove: boolean;
  onRemove: () => void;
};

function CredentialListRow({
  credentialId,
  credential,
  index,
  editable,
  canRemove,
  onRemove,
}: CredentialListRowProps) {
  const detailQuery = useCredentialQuery(credentialId, {
    enabled: !credential,
  });
  const resolvedCredential = credential ?? detailQuery.data;
  const label =
    resolvedCredential?.name ??
    (detailQuery.isPending
      ? "Loading credential..."
      : isCredentialNotFoundError(detailQuery.error)
        ? "Credential not found"
        : "Couldn't load credential.");

  return (
    <div className="flex items-center gap-2 rounded-md border border-border/60 bg-slate-elevation1/40 px-2 py-1.5">
      <span className="flex size-5 shrink-0 items-center justify-center rounded bg-muted text-[10px] text-tertiary-foreground">
        {index + 1}
      </span>
      <span className="min-w-0 flex-1 truncate text-xs text-foreground dark:text-slate-200">
        {label}
      </span>
      {resolvedCredential?.browser_profile_id ? (
        <span
          className="shrink-0 rounded bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground"
          title="Has a saved browser profile - runs with this account keep its logged-in session"
        >
          Profile
        </span>
      ) : null}
      <button
        type="button"
        className="text-muted-foreground transition-colors hover:text-foreground disabled:pointer-events-none disabled:opacity-50 dark:text-slate-500 dark:hover:text-slate-200"
        disabled={!editable || !canRemove}
        onClick={onRemove}
        aria-label={`Remove ${label}`}
      >
        <Cross2Icon className="size-3.5" />
      </button>
    </div>
  );
}

// Function to generate a unique credential parameter key
function generateDefaultCredentialParameterKey(existingKeys: string[]): string {
  const baseName = "credentials";

  // Check if "credentials" is available
  if (!existingKeys.includes(baseName)) {
    return baseName;
  }

  // Find the next available number
  let counter = 1;
  while (existingKeys.includes(`${baseName}_${counter}`)) {
    counter++;
  }

  return `${baseName}_${counter}`;
}

function LoginBlockCredentialSelector({
  nodeId,
  value,
  onChange,
  editable = true,
  onUrlAutoFill,
  currentUrl,
  onInstructionsAutoFill,
  currentInstructions,
}: Props) {
  const { setIsOpen, setType } = useCredentialModalState();
  const nodes = useNodes<AppNode>();
  const { updateNodeData } = useReactFlow<AppNode>();
  const [rotationDraft, setRotationDraft] = useState(false);
  const [rotationQuery, setRotationQuery] = useState("");
  const [debouncedRotationQuery] = useDebounce(rotationQuery, 300);
  const [fallbackDraft, setFallbackDraft] = useState(false);
  const {
    parameters: workflowParameters,
    setParameters: setWorkflowParameters,
  } = useWorkflowParametersStore();
  const setHasChanges = useWorkflowHasChangesStore(
    (state) => state.setHasChanges,
  );
  const readOnlyScope = useWorkflowScopeReadOnly();
  const credentialParameters = workflowParameters.filter(
    (parameter) =>
      parameter.parameterType === "credential" ||
      parameter.parameterType === "onepassword",
  );
  const skyvernCredentialSourceAvailable =
    useSkyvernCredentialSourceAvailable();
  const { data: credentials = [], isLoading } = useCredentialsQuery({
    enabled: skyvernCredentialSourceAvailable,
    page_size: 100,
  });

  const selectedSkyvernCredentialParameter = useMemo(() => {
    if (!value) return undefined;
    const parameter = credentialParameters.find((p) => p.key === value);
    if (!parameter || !parameterIsSkyvernCredential(parameter)) {
      return undefined;
    }
    return parameter;
  }, [value, credentialParameters]);

  useEffect(() => {
    setRotationDraft(false);
    setFallbackDraft(false);
  }, [value]);

  // Determine which credential is currently selected (by credential_id)
  // This handles multiple cases:
  // 1. Skyvern credential parameters (have credentialId)
  // 2. Workflow inputs with credential_id type and default value
  const selectedCredentialId = useMemo(() => {
    if (!value) return undefined;

    // Check if it's a credential parameter
    const credentialParam = credentialParameters.find((p) => p.key === value);
    if (credentialParam && parameterIsSkyvernCredential(credentialParam)) {
      return credentialParam.credentialId;
    }

    // Check if it's a workflow input with credential_id type and default value
    const workflowParam = workflowParameters.find(
      (p) =>
        p.parameterType === "workflow" &&
        p.key === value &&
        p.dataType === "credential_id" &&
        typeof p.defaultValue === "string" &&
        p.defaultValue,
    );
    if (workflowParam && workflowParam.parameterType === "workflow") {
      return workflowParam.defaultValue as string;
    }

    return undefined;
  }, [value, credentialParameters, workflowParameters]);

  const selectedCredentialFromList = useMemo(
    () =>
      credentials.find(
        (credential) => credential.credential_id === selectedCredentialId,
      ),
    [credentials, selectedCredentialId],
  );
  const selectedCredentialQuery = useCredentialQuery(selectedCredentialId, {
    enabled: skyvernCredentialSourceAvailable && !selectedCredentialFromList,
  });
  const selectedCredential =
    selectedCredentialFromList ?? selectedCredentialQuery.data;
  const isCredentialMissing = isCredentialNotFoundError(
    selectedCredentialQuery.error,
  );
  const credentialsWithSelected = useMemo(() => {
    if (!selectedCredential || selectedCredentialFromList) {
      return credentials;
    }
    return [...credentials, selectedCredential];
  }, [credentials, selectedCredential, selectedCredentialFromList]);

  useLoginGoalAutoFill({
    editable,
    selectedCredentialId,
    credentials: credentialsWithSelected,
    currentGoal: currentInstructions ?? "",
    // Marks unsaved so a prefill isn't silently lost on navigation; skipped in read-only scope.
    onAutoFill: (goal) => {
      onInstructionsAutoFill?.(goal);
      if (!readOnlyScope) {
        setHasChanges(true);
      }
    },
  });

  const rotationCredentialIds = useMemo(() => {
    const sourceIds = selectedSkyvernCredentialParameter?.credentialIds?.length
      ? selectedSkyvernCredentialParameter.credentialIds
      : selectedCredentialId
        ? [selectedCredentialId]
        : [];

    return sourceIds.filter((id, index, ids): id is string => {
      return typeof id === "string" && ids.indexOf(id) === index;
    });
  }, [selectedSkyvernCredentialParameter, selectedCredentialId]);

  const fallbackCredentialIds = useMemo(() => {
    return (
      selectedSkyvernCredentialParameter?.fallbackCredentialIds ?? []
    ).filter((id, index, ids): id is string => {
      return typeof id === "string" && ids.indexOf(id) === index;
    });
  }, [selectedSkyvernCredentialParameter]);

  const rotationIsSaved = rotationCredentialIds.length > 1;
  const rotationMode =
    Boolean(selectedSkyvernCredentialParameter) &&
    (rotationDraft || rotationIsSaved);
  const {
    data: rotationCredentials = [],
    isFetching: rotationCredentialsAreFetching,
  } = useCredentialsQuery({
    enabled: skyvernCredentialSourceAvailable && rotationMode,
    page_size: 100,
    search: debouncedRotationQuery.trim() || undefined,
    placeholderData: keepPreviousData,
  });
  const fallbackIsSaved = fallbackCredentialIds.length > 0;
  const fallbackMode =
    Boolean(selectedSkyvernCredentialParameter) &&
    (fallbackDraft || fallbackIsSaved);

  const workflowStartNode = useMemo<
    { id: string; data: WorkflowStartNodeData } | undefined
  >(() => {
    const node = nodes.find(isStartNode);
    if (!node || !isWorkflowStartNodeData(node.data)) {
      return undefined;
    }
    return { id: node.id, data: node.data };
  }, [nodes]);

  // User-authored credential variables (custom-key Skyvern params, or workflow
  // credential_id params) surface their variable name; auto-generated keys keep
  // the plain credential-name render.
  const selectedCredentialVariable = useMemo(() => {
    if (!value || !selectedCredentialId) return undefined;

    const param = workflowParameters.find((p) => p.key === value);
    if (!param) return undefined;

    const isUserAuthored =
      (param.parameterType === "credential" &&
        parameterIsSkyvernCredential(param) &&
        !isAutoGeneratedCredentialKey(param.key)) ||
      (param.parameterType === "workflow" &&
        param.dataType === "credential_id");
    if (!isUserAuthored) return undefined;

    const credentialName = selectedCredential?.name;
    if (!credentialName || credentialName === param.key) return undefined;
    return { key: param.key, credentialName };
  }, [value, selectedCredentialId, workflowParameters, selectedCredential]);

  const wrappedCredentialIds = useMemo(
    () => computeWrappedCredentialIds(credentialParameters),
    [credentialParameters],
  );

  if (skyvernCredentialSourceAvailable && isLoading) {
    return <Skeleton className="h-8 w-full" />;
  }

  const rotationCredentialOptions = rotationCredentials.map((credential) => ({
    label: credential.name,
    value: credential.credential_id,
    hasBrowserProfile: !!credential.browser_profile_id,
    browserProfileUrl: credential.tested_url ?? null,
  }));

  const fallbackCredentialOptions = credentials
    .filter(
      (credential) =>
        !fallbackCredentialIds.includes(credential.credential_id) &&
        credential.credential_id !== selectedCredentialId,
    )
    .map((credential) => ({
      label: credential.name,
      value: credential.credential_id,
      hasBrowserProfile: !!credential.browser_profile_id,
      browserProfileUrl: credential.tested_url ?? null,
    }));

  // Auto-generated Skyvern wrappers are hidden (they back a direct credential
  // pick); user-authored Skyvern params and external vault params are listed.
  // Workflow credential_id params are authored in the Parameters panel, not here.
  const credentialParameterOptions = credentialParameters
    .filter((parameter) => {
      if (
        parameterIsSkyvernCredential(parameter) &&
        isAutoGeneratedCredentialKey(parameter.key)
      ) {
        return false;
      }
      return (
        parameterIsSkyvernCredential(parameter) ||
        parameterIsBitwardenCredential(parameter) ||
        parameterIsOnePasswordCredential(parameter) ||
        parameterIsAzureVaultCredential(parameter)
      );
    })
    .map((parameter) => ({
      label: parameter.key,
      value: parameter.key,
    }));

  const valueIsParameterOption = credentialParameterOptions.some(
    (option) => option.value === value,
  );
  const selectValue = valueIsParameterOption
    ? (value ?? "")
    : (selectedCredentialId ?? value ?? "");

  const writeRotationCredentialIds = (credentialIds: Array<string>) => {
    if (!selectedSkyvernCredentialParameter || credentialIds.length === 0) {
      return;
    }

    const orderedCredentialIds = credentialIds.filter((id, index, ids) => {
      return ids.indexOf(id) === index;
    });
    const firstCredentialId = orderedCredentialIds[0];
    if (!firstCredentialId) {
      return;
    }

    const newParameters = workflowParameters.map((parameter) => {
      if (
        parameter.key !== selectedSkyvernCredentialParameter.key ||
        parameter.parameterType !== "credential" ||
        !parameterIsSkyvernCredential(parameter)
      ) {
        return parameter;
      }

      if (orderedCredentialIds.length < 2) {
        return {
          ...parameter,
          credentialId: firstCredentialId,
          credentialIds: null,
          selectionStrategy: null,
          dataType: undefined,
        };
      }

      return {
        ...parameter,
        credentialId: firstCredentialId,
        credentialIds: orderedCredentialIds,
        selectionStrategy: ROTATION_SELECTION_STRATEGY,
        dataType: undefined,
      };
    });

    setWorkflowParameters(newParameters);
    setHasChanges(true);
  };

  const writeFallbackCredentialIds = (credentialIds: Array<string>) => {
    if (!selectedSkyvernCredentialParameter) {
      return;
    }

    const orderedCredentialIds = credentialIds.filter((id, index, ids) => {
      return ids.indexOf(id) === index;
    });

    const newParameters = workflowParameters.map((parameter) => {
      if (
        parameter.key !== selectedSkyvernCredentialParameter.key ||
        parameter.parameterType !== "credential" ||
        !parameterIsSkyvernCredential(parameter)
      ) {
        return parameter;
      }

      if (orderedCredentialIds.length === 0) {
        return {
          ...parameter,
          fallbackCredentialIds: null,
          fallbackTrigger: null,
        };
      }

      return {
        ...parameter,
        fallbackCredentialIds: orderedCredentialIds,
        fallbackTrigger: parameter.fallbackTrigger ?? null,
      };
    });

    setWorkflowParameters(newParameters);
    setHasChanges(true);
  };

  const writeFallbackTrigger = (fallbackTrigger: CredentialFallbackTrigger) => {
    if (
      !selectedSkyvernCredentialParameter ||
      fallbackCredentialIds.length === 0
    ) {
      return;
    }

    const newParameters = workflowParameters.map((parameter) => {
      if (
        parameter.key !== selectedSkyvernCredentialParameter.key ||
        parameter.parameterType !== "credential" ||
        !parameterIsSkyvernCredential(parameter)
      ) {
        return parameter;
      }

      return {
        ...parameter,
        fallbackTrigger,
      };
    });

    setWorkflowParameters(newParameters);
    setHasChanges(true);
  };

  const toggleRotationCredential = (credentialId: string) => {
    if (!editable) return;
    const nextCredentialIds = rotationCredentialIds.includes(credentialId)
      ? rotationCredentialIds.filter((id) => id !== credentialId)
      : [...rotationCredentialIds, credentialId];

    if (nextCredentialIds.length === 0) {
      return;
    }

    writeRotationCredentialIds(nextCredentialIds);
    if (nextCredentialIds.length < 2) {
      setRotationDraft(false);
    }
  };

  const addFallbackCredential = (credentialId: string) => {
    if (!editable || fallbackCredentialIds.includes(credentialId)) return;
    writeFallbackCredentialIds([...fallbackCredentialIds, credentialId]);
  };

  const removeFallbackCredential = (credentialId: string) => {
    if (!editable) return;
    const nextCredentialIds = fallbackCredentialIds.filter(
      (id) => id !== credentialId,
    );
    writeFallbackCredentialIds(nextCredentialIds);
    if (nextCredentialIds.length === 0) {
      setFallbackDraft(false);
    }
  };

  const disableRotation = () => {
    if (!editable) return;
    if (rotationCredentialIds.length > 0) {
      writeRotationCredentialIds([rotationCredentialIds[0]!]);
    }
    setRotationDraft(false);
  };

  const setRunSequentially = (checked: boolean) => {
    if (!workflowStartNode) {
      return;
    }
    updateNodeData(workflowStartNode.id, {
      runSequentially: checked,
      sequentialKey: checked ? workflowStartNode.data.sequentialKey : null,
    });
    setHasChanges(true);
  };

  const handleCredentialChange = (
    newValue: string,
    selection: CredentialComboboxSelection,
  ) => {
    if (!editable) return;

    let newParameters = [...workflowParameters];
    const loginNodes = nodes
      .filter((node) => node.id !== nodeId)
      .filter(isLoginNode);
    const currentParameter = workflowParameters.find(
      (parameter): parameter is SkyvernCredential => {
        if (parameter.parameterType !== "credential") return false;
        if (!parameterIsSkyvernCredential(parameter)) return false;
        if (!isAutoGeneratedCredentialKey(parameter.key)) return false;
        return parameter.key === value;
      },
    );
    const isUsedInOtherLoginNodes =
      value &&
      loginNodes.some((node) => node.data.parameterKeys.includes(value));
    const deleteOldParameter = currentParameter && !isUsedInOtherLoginNodes;

    // The new primary may not be its own fallback.
    const carriedFallbackCredentialIds = deleteOldParameter
      ? (currentParameter.fallbackCredentialIds ?? []).filter(
          (credentialId) => credentialId !== newValue,
        )
      : [];
    const carriedFallbackTrigger = deleteOldParameter
      ? (currentParameter.fallbackTrigger ?? null)
      : null;

    if (deleteOldParameter) {
      newParameters = newParameters.filter(
        (parameter) => parameter.key !== value,
      );
    }

    const selectedOptionCredential =
      selection.type === "credential" ? selection.credential : undefined;
    let parameterKeyToUse = newValue;

    if (selectedOptionCredential) {
      const existingParameter = newParameters.find((parameter) => {
        return (
          parameter.parameterType === "credential" &&
          parameterIsSkyvernCredential(parameter) &&
          parameter.credentialId === newValue &&
          (parameter.credentialIds?.length ?? 0) < 2
        );
      });

      if (existingParameter) {
        // Reuse the existing parameter; carry the outgoing wrapper's fallback
        // config onto it when it has none of its own.
        parameterKeyToUse = existingParameter.key;
        if (
          carriedFallbackCredentialIds.length > 0 &&
          existingParameter.parameterType === "credential" &&
          parameterIsSkyvernCredential(existingParameter) &&
          (existingParameter.fallbackCredentialIds?.length ?? 0) === 0
        ) {
          newParameters = newParameters.map((parameter) => {
            if (
              parameter.key !== existingParameter.key ||
              parameter.parameterType !== "credential" ||
              !parameterIsSkyvernCredential(parameter)
            ) {
              return parameter;
            }
            return {
              ...parameter,
              fallbackCredentialIds: carriedFallbackCredentialIds,
              fallbackTrigger: carriedFallbackTrigger,
            };
          });
        }
      } else {
        const existingKeys = newParameters.map((parameter) => parameter.key);
        const newKey = generateDefaultCredentialParameterKey(existingKeys);
        parameterKeyToUse = newKey;
        newParameters = [
          ...newParameters,
          {
            parameterType: "credential",
            credentialId: newValue,
            key: newKey,
            ...(carriedFallbackCredentialIds.length > 0 && {
              fallbackCredentialIds: carriedFallbackCredentialIds,
              fallbackTrigger: carriedFallbackTrigger,
            }),
          },
        ];
      }
    }

    setWorkflowParameters(newParameters);
    setHasChanges(true);
    setRotationDraft(false);
    onChange?.(parameterKeyToUse);

    if (selectedOptionCredential?.tested_url && !currentUrl?.trim()) {
      onUrlAutoFill?.(selectedOptionCredential.tested_url);
    }
  };

  const renderCredentialItem = (credential: CredentialApiResponse) => (
    <div className="flex items-center gap-2">
      <span>{credential.name}</span>
      {credential.browser_profile_id ? (
        <>
          <span className="rounded bg-green-100 px-1.5 py-0.5 text-[10px] text-green-700 dark:bg-green-900/40 dark:text-green-400">
            saved-profile
          </span>
          {credential.tested_url ? (
            <span className="text-[10px] text-muted-foreground">
              {getHostname(credential.tested_url)}
            </span>
          ) : null}
        </>
      ) : null}
    </div>
  );

  const renderSelectedValue = (state: SelectedValueState) => {
    if (state.isNotFound) {
      return (
        <div className="flex items-center gap-2 text-red-500">
          <ExclamationTriangleIcon className="size-4" />
          <span>Credential not found</span>
        </div>
      );
    }
    if (selectedCredentialVariable) {
      return (
        <div className="flex min-w-0 flex-col items-start text-left">
          <span className="truncate">{selectedCredentialVariable.key}</span>
          <span className="truncate text-xs text-muted-foreground">
            defaults to credential: {selectedCredentialVariable.credentialName}
          </span>
        </div>
      );
    }
    return undefined;
  };

  const fallbackTrigger =
    selectedSkyvernCredentialParameter?.fallbackTrigger ??
    DEFAULT_FALLBACK_TRIGGER;

  const fallbackSection = selectedSkyvernCredentialParameter ? (
    fallbackMode ? (
      <div className="mt-3 space-y-2 border-t border-border pt-3">
        <div className="space-y-1">
          <span className="text-xs text-foreground dark:text-slate-300">
            Fallback credentials
          </span>
          <p className="text-[11px] leading-4 text-muted-foreground dark:text-slate-500">
            If a run fails, Skyvern automatically retries it with the next
            fallback credential.
          </p>
        </div>
        {/* modal: an outside click must only dismiss the picker — non-modal
            popovers let the same click hit the canvas pane, which deselects
            the block and closes the whole config panel. */}
        <Popover modal>
          <PopoverTrigger asChild>
            <Button
              type="button"
              variant="outline"
              className="h-auto min-h-10 w-full justify-between px-3 py-2 text-left text-xs font-normal"
              disabled={!editable || fallbackCredentialOptions.length === 0}
            >
              <span className="truncate">
                {fallbackCredentialIds.length > 0
                  ? `${fallbackCredentialIds.length} fallback ${
                      fallbackCredentialIds.length === 1
                        ? "credential"
                        : "credentials"
                    }`
                  : "Add fallback credentials"}
              </span>
              <ChevronDownIcon className="ml-2 size-4 shrink-0 text-muted-foreground" />
            </Button>
          </PopoverTrigger>
          <PopoverContent
            className="w-[28rem] p-0"
            align="start"
            // Escape must only dismiss the picker; without this it bubbles to
            // the editor's window listener, which closes the whole block panel.
            onEscapeKeyDown={(event) => event.stopPropagation()}
          >
            <Command>
              <CommandInput placeholder="Search credentials..." />
              <CommandList>
                <CommandEmpty>No credentials found.</CommandEmpty>
                <CommandGroup>
                  {fallbackCredentialOptions.map((option) => (
                    <CommandItem
                      key={option.value}
                      className="cursor-pointer"
                      onSelect={() => addFallbackCredential(option.value)}
                    >
                      <div
                        className={cn(
                          "mr-2 flex size-4 items-center justify-center rounded-sm border border-primary",
                          "opacity-50 [&_svg]:invisible",
                        )}
                      >
                        <CheckIcon className="size-4" />
                      </div>
                      <div className="flex min-w-0 items-center gap-2">
                        <span className="truncate">{option.label}</span>
                        {option.hasBrowserProfile ? (
                          <span className="rounded bg-green-100 px-1.5 py-0.5 text-[10px] text-green-700 dark:bg-green-900/40 dark:text-green-400">
                            saved-profile
                          </span>
                        ) : null}
                        {option.browserProfileUrl ? (
                          <span className="truncate text-[10px] text-muted-foreground">
                            {getHostname(option.browserProfileUrl)}
                          </span>
                        ) : null}
                      </div>
                    </CommandItem>
                  ))}
                </CommandGroup>
              </CommandList>
            </Command>
          </PopoverContent>
        </Popover>

        {fallbackCredentialIds.length > 0 ? (
          <>
            <div className="space-y-1">
              {fallbackCredentialIds.map((credentialId, index) => (
                <CredentialListRow
                  key={credentialId}
                  credentialId={credentialId}
                  credential={credentials.find(
                    (credential) => credential.credential_id === credentialId,
                  )}
                  index={index}
                  editable={editable}
                  canRemove
                  onRemove={() => removeFallbackCredential(credentialId)}
                />
              ))}
            </div>
            <div className="space-y-1">
              <span className="text-xs text-foreground dark:text-slate-300">
                Retry failed runs
              </span>
              <Select
                disabled={!editable}
                value={fallbackTrigger}
                onValueChange={(value) =>
                  writeFallbackTrigger(value as CredentialFallbackTrigger)
                }
              >
                <SelectTrigger className="h-9 w-full text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="credential_failures">
                    On credential failures
                  </SelectItem>
                  <SelectItem value="any_failure">On any failure</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </>
        ) : null}
      </div>
    ) : (
      <button
        type="button"
        className="mt-2 inline-flex items-center gap-1 text-xs text-muted-foreground transition-colors hover:text-foreground disabled:pointer-events-none disabled:opacity-50 dark:hover:text-slate-200"
        disabled={!editable}
        onClick={() => setFallbackDraft(true)}
      >
        <PlusIcon className="size-3" />
        Add fallback credentials
      </button>
    )
  ) : null;

  if (rotationMode) {
    return (
      <>
        <div className="space-y-2">
          {/* modal: an outside click must only dismiss the picker — non-modal
              popovers let the same click hit the canvas pane, which deselects
              the block and closes the whole config panel. */}
          <Popover modal>
            <PopoverTrigger asChild>
              <Button
                type="button"
                variant="outline"
                className="h-auto min-h-10 w-full justify-between px-3 py-2 text-left text-xs font-normal"
                disabled={!editable}
              >
                <span className="truncate">
                  {rotationCredentialIds.length > 1
                    ? `Rotates across ${rotationCredentialIds.length} credentials`
                    : "Add credentials to rotate"}
                </span>
                <ChevronDownIcon className="ml-2 size-4 shrink-0 text-muted-foreground" />
              </Button>
            </PopoverTrigger>
            <PopoverContent
              className="w-[28rem] p-0"
              align="start"
              // Escape must only dismiss the picker; without this it bubbles to
              // the editor's window listener, which closes the whole block panel.
              onEscapeKeyDown={(event) => event.stopPropagation()}
            >
              <Command shouldFilter={false}>
                <CommandInput
                  placeholder="Search credentials..."
                  value={rotationQuery}
                  onValueChange={setRotationQuery}
                />
                <CommandList>
                  {rotationCredentialOptions.length === 0 ? (
                    <CommandEmpty>
                      {rotationCredentialsAreFetching
                        ? "Searching credentials..."
                        : "No credentials found."}
                    </CommandEmpty>
                  ) : null}
                  <CommandGroup>
                    {rotationCredentialOptions.map((option) => {
                      const isSelected = rotationCredentialIds.includes(
                        option.value,
                      );
                      return (
                        <CommandItem
                          key={option.value}
                          className="cursor-pointer"
                          onSelect={() =>
                            toggleRotationCredential(option.value)
                          }
                        >
                          <div
                            className={cn(
                              "mr-2 flex size-4 items-center justify-center rounded-sm border border-primary",
                              isSelected
                                ? "bg-primary text-primary-foreground"
                                : "opacity-50 [&_svg]:invisible",
                            )}
                          >
                            <CheckIcon className="size-4" />
                          </div>
                          <div className="flex min-w-0 items-center gap-2">
                            <span className="truncate">{option.label}</span>
                            {option.hasBrowserProfile ? (
                              <span className="rounded bg-green-100 px-1.5 py-0.5 text-[10px] text-green-700 dark:bg-green-900/40 dark:text-green-400">
                                saved-profile
                              </span>
                            ) : null}
                            {option.browserProfileUrl ? (
                              <span className="truncate text-[10px] text-muted-foreground">
                                {getHostname(option.browserProfileUrl)}
                              </span>
                            ) : null}
                          </div>
                        </CommandItem>
                      );
                    })}
                  </CommandGroup>
                </CommandList>
              </Command>
            </PopoverContent>
          </Popover>

          <div className="space-y-1">
            {rotationCredentialIds.map((credentialId, index) => (
              <CredentialListRow
                key={credentialId}
                credentialId={credentialId}
                credential={rotationCredentials.find(
                  (credential) => credential.credential_id === credentialId,
                )}
                index={index}
                editable={editable}
                canRemove={rotationCredentialIds.length > 1}
                onRemove={() => toggleRotationCredential(credentialId)}
              />
            ))}
          </div>

          {rotationCredentialIds.length > 1 ? (
            <div className="flex items-start gap-2 text-xs text-muted-foreground">
              <div className="space-y-0.5">
                <span>Disable parallel runs</span>
                <p className="text-[11px] leading-4 text-muted-foreground dark:text-slate-500">
                  Queues this workflow's runs one at a time so rotated accounts
                  never log in simultaneously.
                </p>
              </div>
              <Switch
                className="ml-auto shrink-0"
                checked={
                  workflowStartNode
                    ? workflowStartNode.data.runSequentially
                    : false
                }
                disabled={!editable || !workflowStartNode}
                onCheckedChange={setRunSequentially}
              />
            </div>
          ) : null}

          <button
            type="button"
            className="text-xs text-muted-foreground transition-colors hover:text-foreground disabled:pointer-events-none disabled:opacity-50 dark:hover:text-slate-200"
            disabled={!editable}
            onClick={disableRotation}
          >
            Use single credential
          </button>
          <p className="text-[11px] leading-4 text-muted-foreground dark:text-slate-500">
            Fallback credentials can&apos;t be combined with credential
            rotation.
          </p>
        </div>
        <CredentialsModal
          onCredentialCreated={(id) => {
            if (!editable) return;
            const existingKeys = workflowParameters.map((param) => param.key);
            const newKey = generateDefaultCredentialParameterKey(existingKeys);

            setWorkflowParameters([
              ...workflowParameters,
              {
                parameterType: "credential",
                credentialId: id,
                key: newKey,
              },
            ]);
            setHasChanges(true);
            onChange?.(newKey);
          }}
        />
      </>
    );
  }

  return (
    <>
      <CredentialCombobox
        disabled={!editable}
        value={selectValue}
        selectedCredentialId={selectedCredentialId}
        onValueChange={handleCredentialChange}
        extraOptions={credentialParameterOptions}
        onAddNew={() => {
          setIsOpen(true);
          setType(CredentialModalTypes.PASSWORD);
        }}
        renderCredentialItem={renderCredentialItem}
        renderSelectedValue={renderSelectedValue}
        query={{
          enabled: skyvernCredentialSourceAvailable,
          excludeCredentialIds: wrappedCredentialIds,
        }}
        triggerProps={{
          className: isCredentialMissing
            ? "h-auto min-h-10 w-full border-red-500 text-red-500"
            : "h-auto min-h-10 w-full",
        }}
      />
      {fallbackMode ? (
        <p className="mt-2 text-[11px] leading-4 text-muted-foreground dark:text-slate-500">
          Credential rotation can&apos;t be combined with fallback credentials.
        </p>
      ) : selectedSkyvernCredentialParameter &&
        selectedCredentialId &&
        !isCredentialMissing ? (
        <button
          type="button"
          className="mt-2 inline-flex items-center gap-1 text-xs text-muted-foreground transition-colors hover:text-foreground disabled:pointer-events-none disabled:opacity-50 dark:hover:text-slate-200"
          disabled={!editable}
          onClick={() => setRotationDraft(true)}
        >
          <ReloadIcon className="size-3" />
          Rotate between multiple credentials
        </button>
      ) : null}
      {fallbackSection}
      <CredentialsModal
        onCredentialCreated={(id) => {
          if (!editable) return;
          const existingKeys = workflowParameters.map((param) => param.key);
          const newKey = generateDefaultCredentialParameterKey(existingKeys);

          // Update Zustand store first, then call onChange
          setWorkflowParameters([
            ...workflowParameters,
            {
              parameterType: "credential",
              credentialId: id,
              key: newKey,
            },
          ]);
          setHasChanges(true);
          onChange?.(newKey);
        }}
      />
    </>
  );
}

export { LoginBlockCredentialSelector };
