"""Browser-side expressions used by Workflow Copilot composition inspection."""

from __future__ import annotations

# Keep stripped-body evaluate results under the shared MCP response cap while
# preserving as much below-fold page structure as possible.
COMPOSITION_STRIPPED_HTML_MAX_CHARS = 135000
COMPOSITION_STRIPPED_HTML_EXPRESSION = (
    "(() => {"
    "  const b = document.body; if (!b) return '';"
    "  const c = b.cloneNode(true);"
    "  c.querySelectorAll('script,style,noscript,svg,template,iframe,canvas,link').forEach(n => n.remove());"
    "  const w = document.createTreeWalker(c, NodeFilter.SHOW_COMMENT, null);"
    "  const comments = []; while (w.nextNode()) comments.push(w.currentNode); comments.forEach(n => n.remove());"
    "  const h = c.innerHTML.replace(/>\\s+</g, '><').replace(/\\s{2,}/g, ' ');"
    f"  return h.length > {COMPOSITION_STRIPPED_HTML_MAX_CHARS} ? "
    f"h.slice(0, {COMPOSITION_STRIPPED_HTML_MAX_CHARS}) : h;"
    "})()"
)

COMPOSITION_VISUAL_OBSTRUCTION_CANDIDATES_EXPRESSION = (
    "(() => {"
    "  const body = document.body; if (!body) return [];"
    "  const viewportWidth = window.innerWidth || document.documentElement.clientWidth || 0;"
    "  const viewportHeight = window.innerHeight || document.documentElement.clientHeight || 0;"
    "  const highZIndex = (value) => {"
    "    const numeric = Number.parseFloat(value);"
    "    return Number.isFinite(numeric) && numeric >= 10;"
    "  };"
    "  const visible = (style, rect) => ("
    "    style.display !== 'none' && style.visibility !== 'hidden' &&"
    "    Number.parseFloat(style.opacity || '1') > 0.05 && rect.width > 0 && rect.height > 0"
    "  );"
    "  const coversViewport = (rect) => ("
    "    viewportWidth > 0 && viewportHeight > 0 &&"
    "    rect.left <= viewportWidth * 0.05 && rect.top <= viewportHeight * 0.05 &&"
    "    rect.right >= viewportWidth * 0.95 && rect.bottom >= viewportHeight * 0.95"
    "  );"
    "  const hasControl = (element) => Array.from("
    "    element.querySelectorAll('button,a,input,[role=\"button\"]')"
    "  ).some((control) => {"
    "    const text = `${control.innerText || ''} ${control.value || ''} "
    "${control.getAttribute('aria-label') || ''}`.trim();"
    "    if (!text) return false;"
    "    const tag = control.tagName.toLowerCase();"
    "    const type = (control.getAttribute('type') || '').toLowerCase();"
    "    return tag !== 'input' || ['button', 'submit', 'reset'].includes(type);"
    "  });"
    "  const candidates = [];"
    "  for (const element of Array.from(body.querySelectorAll('*'))) {"
    "    if (candidates.length >= 5) break;"
    "    const style = window.getComputedStyle(element);"
    "    if (!['fixed', 'sticky'].includes(style.position)) continue;"
    "    if (!highZIndex(style.zIndex)) continue;"
    "    const rect = element.getBoundingClientRect();"
    "    if (!visible(style, rect) || !coversViewport(rect)) continue;"
    "    candidates.push({"
    "      source: 'computed_style',"
    "      position: style.position,"
    "      coverage: 'viewport',"
    "      has_visible_controls: hasControl(element),"
    "    });"
    "  }"
    "  return candidates;"
    "})()"
)
