// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export type ActionBlockParametersItem =
    | Skyvern.ActionBlockParametersItem.AwsSecret
    | Skyvern.ActionBlockParametersItem.AzureSecret
    | Skyvern.ActionBlockParametersItem.AzureVaultCredential
    | Skyvern.ActionBlockParametersItem.BitwardenCreditCardData
    | Skyvern.ActionBlockParametersItem.BitwardenLoginCredential
    | Skyvern.ActionBlockParametersItem.BitwardenSensitiveInformation
    | Skyvern.ActionBlockParametersItem.Context
    | Skyvern.ActionBlockParametersItem.Credential
    | Skyvern.ActionBlockParametersItem.Onepassword
    | Skyvern.ActionBlockParametersItem.Output
    | Skyvern.ActionBlockParametersItem.Workflow;

export namespace ActionBlockParametersItem {
    export interface AwsSecret extends Skyvern.AwsSecretParameter {
        parameter_type: "aws_secret";
    }

    export interface AzureSecret extends Skyvern.AzureSecretParameter {
        parameter_type: "azure_secret";
    }

    export interface AzureVaultCredential extends Skyvern.AzureVaultCredentialParameter {
        parameter_type: "azure_vault_credential";
    }

    export interface BitwardenCreditCardData extends Skyvern.BitwardenCreditCardDataParameter {
        parameter_type: "bitwarden_credit_card_data";
    }

    export interface BitwardenLoginCredential extends Skyvern.BitwardenLoginCredentialParameter {
        parameter_type: "bitwarden_login_credential";
    }

    export interface BitwardenSensitiveInformation extends Skyvern.BitwardenSensitiveInformationParameter {
        parameter_type: "bitwarden_sensitive_information";
    }

    export interface Context extends Skyvern.ContextParameter {
        parameter_type: "context";
    }

    export interface Credential extends Skyvern.CredentialParameter {
        parameter_type: "credential";
    }

    export interface Onepassword extends Skyvern.OnePasswordCredentialParameter {
        parameter_type: "onepassword";
    }

    export interface Output extends Skyvern.OutputParameter {
        parameter_type: "output";
    }

    export interface Workflow extends Skyvern.WorkflowParameter {
        parameter_type: "workflow";
    }
}
