// This file was auto-generated by Fern from our API Definition.

export interface AzureVaultCredentialParameter {
    key: string;
    description?: string;
    azure_vault_credential_parameter_id: string;
    workflow_id: string;
    vault_name: string;
    username_key: string;
    password_key: string;
    totp_secret_key?: string;
    created_at: string;
    modified_at: string;
    deleted_at?: string;
}
