// This file was auto-generated by Fern from our API Definition.

export interface BitwardenLoginCredentialParameter {
    key: string;
    description?: string;
    bitwarden_login_credential_parameter_id: string;
    workflow_id: string;
    bitwarden_client_id_aws_secret_key: string;
    bitwarden_client_secret_aws_secret_key: string;
    bitwarden_master_password_aws_secret_key: string;
    url_parameter_key?: string;
    bitwarden_collection_id?: string;
    bitwarden_item_id?: string;
    created_at: string;
    modified_at: string;
    deleted_at?: string;
}
