// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface CodeBlock {
    /** Author-facing identifier for a block; unique within a workflow. */
    label: string;
    /** Optional pointer to the next block label when constructing a DAG. Defaults to sequential order when omitted. */
    next_block_label?: string;
    output_parameter: Skyvern.OutputParameter;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    disable_cache?: boolean;
    ignore_workflow_system_prompt?: boolean;
    next_loop_on_failure?: boolean;
    code: string;
    parameters?: Skyvern.CodeBlockParametersItem[];
    prompt?: string;
    steps?: Skyvern.CodeBlockStep[];
    /** JSON schema of the object this block's return produces; keys match the return keys; null when the block returns nothing */
    data_schema?: CodeBlock.DataSchema;
}

export namespace CodeBlock {
    /**
     * JSON schema of the object this block's return produces; keys match the return keys; null when the block returns nothing
     */
    export type DataSchema = Record<string, unknown> | unknown[] | string;
}
