// This file was auto-generated by Fern from our API Definition.

/**
 * Optional billing address fields associated with a credit card credential.
 */
export interface CreditCardBillingAddress {
    /** Billing address line 1 */
    line1?: string;
    /** Billing address line 2 */
    line2?: string;
    /** Billing city */
    city?: string;
    /** Billing state or region */
    state?: string;
    /** Billing state or region code */
    state_code?: string;
    /** Billing postal code */
    postal_code?: string;
    /** Billing country */
    country?: string;
    /** ISO 3166-1 alpha-2 billing country code */
    country_code?: string;
}
