// This file was auto-generated by Fern from our API Definition.

export const CustomLlmProvider = {
    OpenaiCompatible: "openai_compatible",
    Ollama: "ollama",
    Openrouter: "openrouter",
} as const;
export type CustomLlmProvider = (typeof CustomLlmProvider)[keyof typeof CustomLlmProvider];
