// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface CustomLlm {
    id: string;
    organization_id: string;
    config: Skyvern.CustomLlmConfig;
    created_at: string;
    modified_at: string;
    valid: boolean;
}
