// This file was auto-generated by Fern from our API Definition.

export const FileStorageType = {
    S3: "s3",
    Azure: "azure",
    GoogleDrive: "google_drive",
    Sftp: "sftp",
} as const;
export type FileStorageType = (typeof FileStorageType)[keyof typeof FileStorageType];
