// This file was auto-generated by Fern from our API Definition.

/**
 * Response model for a folder
 */
export interface Folder {
    /** Folder title */
    title: string;
    /** Folder description */
    description?: string;
    folder_id: string;
    organization_id: string;
    /** Number of workflows in this folder */
    workflow_count?: number;
    created_at: string;
    modified_at: string;
}
