// This file was auto-generated by Fern from our API Definition.

export interface GoogleSheetsWriteBlockYaml {
    /** Author-facing identifier; must be unique per workflow. */
    label: string;
    /** Optional pointer to the label of the next block. When omitted, it will default to sequential order. See [[s-4bnl]]. */
    next_block_label?: string;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    ignore_workflow_system_prompt?: boolean;
    next_loop_on_failure?: boolean;
    spreadsheet_url: string;
    sheet_name?: string;
    range?: string;
    credential_id?: string;
    write_mode?: GoogleSheetsWriteBlockYaml.WriteMode;
    values?: string;
    column_mapping?: Record<string, string | undefined>;
    create_sheet_if_missing?: boolean;
    parameter_keys?: string[];
}

export namespace GoogleSheetsWriteBlockYaml {
    export const WriteMode = {
        Append: "append",
        Update: "update",
    } as const;
    export type WriteMode = (typeof WriteMode)[keyof typeof WriteMode];
}
