// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface GoogleSheetsReadBlock {
    /** Author-facing identifier for a block; unique within a workflow. */
    label: string;
    /** Optional pointer to the next block label when constructing a DAG. Defaults to sequential order when omitted. */
    next_block_label?: string;
    output_parameter: Skyvern.OutputParameter;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    disable_cache?: boolean;
    ignore_workflow_system_prompt?: boolean;
    next_loop_on_failure?: boolean;
    spreadsheet_url: string;
    sheet_name?: string;
    range?: string;
    credential_id?: string;
    has_header_row?: boolean;
    parameters?: Skyvern.GoogleSheetsReadBlockParametersItem[];
}
