// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface HttpRequestBlock {
    /** Author-facing identifier for a block; unique within a workflow. */
    label: string;
    /** Optional pointer to the next block label when constructing a DAG. Defaults to sequential order when omitted. */
    next_block_label?: string;
    output_parameter: Skyvern.OutputParameter;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    disable_cache?: boolean;
    next_loop_on_failure?: boolean;
    method?: string;
    url?: string;
    headers?: Record<string, string | undefined>;
    body?: Record<string, unknown>;
    files?: Record<string, string | undefined>;
    timeout?: number;
    follow_redirects?: boolean;
    parameters?: Skyvern.HttpRequestBlockParametersItem[];
}
