// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface NavigationBlockYaml {
    label: string;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    navigation_goal: string;
    url?: string;
    title?: string;
    engine?: Skyvern.RunEngine;
    error_code_mapping?: Record<string, string | undefined>;
    max_retries?: number;
    max_steps_per_run?: number;
    parameter_keys?: string[];
    complete_on_download?: boolean;
    download_suffix?: string;
    totp_verification_url?: string;
    totp_identifier?: string;
    cache_actions?: boolean;
    disable_cache?: boolean;
    complete_criterion?: string;
    terminate_criterion?: string;
    complete_verification?: boolean;
    include_action_history_in_verification?: boolean;
}
