// This file was auto-generated by Fern from our API Definition.

export interface OrganizationScheduleItem {
    workflow_schedule_id: string;
    organization_id: string;
    workflow_permanent_id: string;
    workflow_title: string;
    cron_expression: string;
    timezone: string;
    enabled: boolean;
    parameters?: Record<string, unknown>;
    name?: string;
    description?: string;
    next_run?: string;
    created_at: string;
    modified_at: string;
}
