// This file was auto-generated by Fern from our API Definition.

/**
 * Compact schedule projection for the org-wide list endpoint.
 *
 * Intentionally omits `backend_schedule_id` — the list view is for browsing
 * schedules in the dashboard, not for managing the underlying execution-backend
 * binding. Callers that need the backend id should fetch the individual
 * schedule via the per-workflow get endpoint.
 */
export interface OrganizationScheduleItem {
    workflow_schedule_id: string;
    organization_id: string;
    workflow_permanent_id: string;
    workflow_title: string;
    cron_expression: string;
    timezone: string;
    enabled: boolean;
    parameters?: Record<string, unknown>;
    name?: string;
    description?: string;
    next_run?: string;
    created_at: string;
    modified_at: string;
}
