// This file was auto-generated by Fern from our API Definition.

export const OtpType = {
    Totp: "totp",
    MagicLink: "magic_link",
} as const;
export type OtpType = (typeof OtpType)[keyof typeof OtpType];
