// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface PdfFillBlock {
    /** Author-facing identifier for a block; unique within a workflow. */
    label: string;
    /** Optional pointer to the next block label when constructing a DAG. Defaults to sequential order when omitted. */
    next_block_label?: string;
    output_parameter: Skyvern.OutputParameter;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    disable_cache?: boolean;
    ignore_workflow_system_prompt?: boolean;
    next_loop_on_failure?: boolean;
    file_url: string;
    prompt: string;
    payload?: PdfFillBlock.Payload;
    llm_key?: string;
    parameters?: Skyvern.PdfFillBlockParametersItem[];
}

export namespace PdfFillBlock {
    export type Payload = Record<string, unknown> | unknown[] | string;
}
