// This file was auto-generated by Fern from our API Definition.

export const PersistentBrowserType = {
    Msedge: "msedge",
    Chrome: "chrome",
} as const;
export type PersistentBrowserType = (typeof PersistentBrowserType)[keyof typeof PersistentBrowserType];
