// This file was auto-generated by Fern from our API Definition.

export interface RetryRunWebhookRequest {
    /** Optional webhook URL to send the payload to instead of the stored configuration */
    webhook_url?: string;
}
