// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

/**
 * Current tags for a workflow run.
 */
export interface RunTagsResponse {
    workflow_run_id: string;
    tags: Skyvern.TagResponse[];
}
