// This file was auto-generated by Fern from our API Definition.

export interface Script {
    /** Unique identifier for this specific script revision */
    script_revision_id: string;
    /** User-facing script identifier, consistent across versions */
    script_id: string;
    /** ID of the organization that owns this script */
    organization_id: string;
    /** ID of the workflow run or task run that generated this script */
    run_id?: string;
    /** Version number of the script */
    version: number;
    /** Timestamp when the script was created */
    created_at: string;
    /** Timestamp when the script was last modified */
    modified_at: string;
    /** Timestamp when the script was soft deleted */
    deleted_at?: string;
}
