// This file was auto-generated by Fern from our API Definition.

/**
 * One tag to soft-delete: a grouped tag by its ``key``, or a standalone label
 * by its ``value`` (omit the key).
 */
export interface TagDeleteInput {
    /** Group (key) to delete. Use for grouped tags. */
    key?: string;
    /** Label (value) to delete. Use for standalone labels. */
    value?: string;
}
