// This file was auto-generated by Fern from our API Definition.

/**
 * Tag-value color registry entry: the palette color assigned to a grouped
 * (key, value) pair.
 */
export interface TagValue {
    key: string;
    value: string;
    color: string;
    /** Number of non-deleted workflows currently carrying this (key, value) label. */
    workflow_count?: number;
}
