// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface TaskV2Block {
    label: string;
    output_parameter: Skyvern.OutputParameter;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    disable_cache?: boolean;
    prompt: string;
    url?: string;
    totp_verification_url?: string;
    totp_identifier?: string;
    max_iterations?: number;
    max_steps?: number;
}
