// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface TextPromptBlock {
    label: string;
    output_parameter: Skyvern.OutputParameter;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    disable_cache?: boolean;
    llm_key?: string;
    prompt: string;
    parameters?: Skyvern.TextPromptBlockParametersItem[];
    json_schema?: Record<string, unknown>;
}
