// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface WorkflowDefinitionYaml {
    version?: number;
    parameters: Skyvern.WorkflowDefinitionYamlParametersItem[];
    blocks: Skyvern.WorkflowDefinitionYamlBlocksItem[];
    finally_block_label?: string;
    error_code_mapping?: Record<string, string | undefined>;
    workflow_system_prompt?: string;
}
