// This file was auto-generated by Fern from our API Definition.

/**
 * How a workflow run was initiated.
 *
 * - manual: User clicked "Run" in the UI
 * - api: Direct API call to the run endpoint
 * - scheduled: Triggered by a cron schedule
 * - webhook: Triggered by an external system via the webhook endpoint
 */
export const WorkflowRunTriggerType = {
    Manual: "manual",
    Api: "api",
    Scheduled: "scheduled",
    Webhook: "webhook",
} as const;
export type WorkflowRunTriggerType = (typeof WorkflowRunTriggerType)[keyof typeof WorkflowRunTriggerType];
