// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface WorkflowRunBlock {
    workflow_run_block_id: string;
    block_workflow_run_id?: string;
    workflow_run_id: string;
    organization_id: string;
    description?: string;
    parent_workflow_run_block_id?: string;
    block_type: Skyvern.BlockType;
    label?: string;
    status?: string;
    output?: WorkflowRunBlock.Output;
    continue_on_failure?: boolean;
    failure_reason?: string;
    engine?: Skyvern.RunEngine;
    task_id?: string;
    url?: string;
    navigation_goal?: string;
    navigation_payload?: WorkflowRunBlock.NavigationPayload;
    data_extraction_goal?: string;
    data_schema?: WorkflowRunBlock.DataSchema;
    terminate_criterion?: string;
    complete_criterion?: string;
    actions?: Skyvern.Action[];
    created_at: string;
    modified_at: string;
    include_action_history_in_verification?: boolean;
    duration?: number;
    loop_values?: unknown[];
    current_value?: string;
    current_index?: number;
    recipients?: string[];
    attachments?: string[];
    subject?: string;
    body?: string;
    instructions?: string;
    positive_descriptor?: string;
    negative_descriptor?: string;
}

export namespace WorkflowRunBlock {
    export type Output = Record<string, unknown> | unknown[] | string;
    export type NavigationPayload = Record<string, unknown> | unknown[] | string;
    export type DataSchema = Record<string, unknown> | unknown[] | string;
}
