// This file was auto-generated by Fern from our API Definition.

export interface WorkflowTriggerBlockYaml {
    /** Author-facing identifier; must be unique per workflow. */
    label: string;
    /** Optional pointer to the label of the next block. When omitted, it will default to sequential order. See [[s-4bnl]]. */
    next_block_label?: string;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    next_loop_on_failure?: boolean;
    workflow_permanent_id: string;
    payload?: Record<string, unknown>;
    wait_for_completion?: boolean;
    browser_session_id?: string;
    use_parent_browser_session?: boolean;
    parameter_keys?: string[];
}
