// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface WorkflowSchedule {
    workflow_schedule_id: string;
    organization_id: string;
    workflow_permanent_id: string;
    cron_expression?: string;
    interval_seconds?: number;
    first_fire_at?: string;
    run_at?: string;
    dispatch_status?: Skyvern.OneTimeDispatchStatus;
    workflow_run_id?: string;
    timezone: string;
    enabled: boolean;
    parameters?: Record<string, unknown>;
    temporal_schedule_id?: string;
    name?: string;
    description?: string;
    created_at: string;
    modified_at: string;
    deleted_at?: string;
}
