// This file was auto-generated by Fern from our API Definition.

export interface WorkflowSchedule {
    workflow_schedule_id: string;
    organization_id: string;
    workflow_permanent_id: string;
    cron_expression: string;
    timezone: string;
    enabled: boolean;
    parameters?: Record<string, unknown>;
    temporal_schedule_id?: string;
    name?: string;
    description?: string;
    created_at: string;
    modified_at: string;
    deleted_at?: string;
}
