// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export type WorkflowDefinitionYamlParametersItem =
    | Skyvern.WorkflowDefinitionYamlParametersItem.AwsSecret
    | Skyvern.WorkflowDefinitionYamlParametersItem.AzureVaultCredential
    | Skyvern.WorkflowDefinitionYamlParametersItem.BitwardenCreditCardData
    | Skyvern.WorkflowDefinitionYamlParametersItem.BitwardenLoginCredential
    | Skyvern.WorkflowDefinitionYamlParametersItem.BitwardenSensitiveInformation
    | Skyvern.WorkflowDefinitionYamlParametersItem.Context
    | Skyvern.WorkflowDefinitionYamlParametersItem.Credential
    | Skyvern.WorkflowDefinitionYamlParametersItem.Onepassword
    | Skyvern.WorkflowDefinitionYamlParametersItem.Output
    | Skyvern.WorkflowDefinitionYamlParametersItem.Workflow;

export namespace WorkflowDefinitionYamlParametersItem {
    export interface AwsSecret extends Skyvern.AwsSecretParameterYaml {
        parameter_type: "aws_secret";
    }

    export interface AzureVaultCredential extends Skyvern.AzureVaultCredentialParameterYaml {
        parameter_type: "azure_vault_credential";
    }

    export interface BitwardenCreditCardData extends Skyvern.BitwardenCreditCardDataParameterYaml {
        parameter_type: "bitwarden_credit_card_data";
    }

    export interface BitwardenLoginCredential extends Skyvern.BitwardenLoginCredentialParameterYaml {
        parameter_type: "bitwarden_login_credential";
    }

    export interface BitwardenSensitiveInformation extends Skyvern.BitwardenSensitiveInformationParameterYaml {
        parameter_type: "bitwarden_sensitive_information";
    }

    export interface Context extends Skyvern.ContextParameterYaml {
        parameter_type: "context";
    }

    export interface Credential extends Skyvern.CredentialParameterYaml {
        parameter_type: "credential";
    }

    export interface Onepassword extends Skyvern.OnePasswordCredentialParameterYaml {
        parameter_type: "onepassword";
    }

    export interface Output extends Skyvern.OutputParameterYaml {
        parameter_type: "output";
    }

    export interface Workflow extends Skyvern.WorkflowParameterYaml {
        parameter_type: "workflow";
    }
}
