// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../index.js";

export interface WorkflowTriggerBlock {
    /** Author-facing identifier for a block; unique within a workflow. */
    label: string;
    /** Optional pointer to the next block label when constructing a DAG. Defaults to sequential order when omitted. */
    next_block_label?: string;
    output_parameter: Skyvern.OutputParameter;
    continue_on_failure?: boolean;
    model?: Record<string, unknown>;
    disable_cache?: boolean;
    next_loop_on_failure?: boolean;
    workflow_permanent_id: string;
    payload?: Record<string, unknown>;
    wait_for_completion?: boolean;
    browser_session_id?: string;
    use_parent_browser_session?: boolean;
    parameters?: Skyvern.WorkflowTriggerBlockParametersItem[];
}
