from collections.abc import AsyncIterator, Mapping

import structlog
from fastapi import Depends
from starlette.requests import HTTPConnection

from skyvern.forge import app
from skyvern.forge.sdk.services.request_principal import get_request_principal

LOG = structlog.get_logger()

ROUTE_ACTIONS: Mapping[str, str] = {
    "skyvern.forge.sdk.routes.agent_protocol.apply_run_tags": "workflow_run.update",
    "skyvern.forge.sdk.routes.agent_protocol.apply_workflow_tags": "workflow.update",
    "skyvern.forge.sdk.routes.agent_protocol.batch_get_run_tags": "workflow_run.read",
    "skyvern.forge.sdk.routes.agent_protocol.batch_get_run_tags_post": "workflow_run.execute",
    "skyvern.forge.sdk.routes.agent_protocol.batch_get_workflow_tags": "tag.read",
    "skyvern.forge.sdk.routes.agent_protocol.batch_get_workflow_tags_post": "tag.execute",
    "skyvern.forge.sdk.routes.agent_protocol.bulk_cancel_runs": "workflow_run.execute",
    "skyvern.forge.sdk.routes.agent_protocol.cancel_persistent_browser_session_workflow_run": "workflow_run.cancel",
    "skyvern.forge.sdk.routes.agent_protocol.cancel_run": "workflow_run.cancel",
    "skyvern.forge.sdk.routes.agent_protocol.cancel_task": "task.cancel",
    "skyvern.forge.sdk.routes.agent_protocol.cancel_workflow_run": "workflow.cancel",
    "skyvern.forge.sdk.routes.agent_protocol.continue_workflow_run": "workflow.continue",
    "skyvern.forge.sdk.routes.agent_protocol.convert_curl_to_http": "utility.convert",
    "skyvern.forge.sdk.routes.agent_protocol.convert_sop_to_blocks": "workflow.convert",
    "skyvern.forge.sdk.routes.agent_protocol.create_folder": "workflow_folder.create",
    "skyvern.forge.sdk.routes.agent_protocol.create_tag_value": "tag.create",
    "skyvern.forge.sdk.routes.agent_protocol.create_workflow": "workflow.create",
    "skyvern.forge.sdk.routes.agent_protocol.create_workflow_from_prompt": "workflow.create",
    "skyvern.forge.sdk.routes.agent_protocol.create_workflow_legacy": "workflow.create",
    "skyvern.forge.sdk.routes.agent_protocol.delete_file": "file.delete",
    "skyvern.forge.sdk.routes.agent_protocol.delete_folder": "workflow_folder.delete",
    "skyvern.forge.sdk.routes.agent_protocol.delete_run_tag": "workflow_run.delete",
    "skyvern.forge.sdk.routes.agent_protocol.delete_tag_key": "tag.delete",
    "skyvern.forge.sdk.routes.agent_protocol.delete_tag_value": "tag.delete",
    "skyvern.forge.sdk.routes.agent_protocol.delete_workflow": "workflow.delete",
    "skyvern.forge.sdk.routes.agent_protocol.delete_workflow_tag": "workflow.delete",
    "skyvern.forge.sdk.routes.agent_protocol.generate_task": "workflow.execute",
    "skyvern.forge.sdk.routes.agent_protocol.get_actions": "task.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_api_keys": "api_key.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_artifact": "artifact.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_artifact_content": "artifact.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_artifact_signed_url": "artifact.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_artifacts": "artifact.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_browser_types": "browser_type.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_current_organization": "organization.settings.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_folder": "workflow_folder.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_folders": "workflow_folder.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_organizations": "organization.settings.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_run": "workflow_run.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_run_artifacts": "workflow_run.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_run_tag_history": "workflow_run.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_run_tag_suggestions": "workflow_run.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_run_tags": "workflow_run.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_run_timeline": "workflow_run.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_runs": "workflow_run.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_runs_v2": "workflow_run.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_step_artifacts": "task.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_steps": "task.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_task_v1": "task.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_task_v2": "task.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_tasks": "task.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_version": "version.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow": "workflow.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_and_run_from_workflow_run_id": "workflow.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_run": "workflow.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_run_timeline": "workflow.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_run_with_workflow_id": "workflow.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_runs": "workflow.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_runs_by_id": "workflow.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_runs_by_id_legacy": "workflow.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_tag_history": "workflow.read",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_tags": "workflow.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_templates": "workflow.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflow_versions": "workflow.list",
    "skyvern.forge.sdk.routes.agent_protocol.get_workflows": "workflow.list",
    "skyvern.forge.sdk.routes.agent_protocol.heartbeat": "health.read",
    "skyvern.forge.sdk.routes.agent_protocol.import_workflow_from_pdf": "workflow.create",
    "skyvern.forge.sdk.routes.agent_protocol.list_tag_keys": "tag.list",
    "skyvern.forge.sdk.routes.agent_protocol.list_tag_values": "tag.list",
    "skyvern.forge.sdk.routes.agent_protocol.models": "model.read",
    "skyvern.forge.sdk.routes.agent_protocol.rename_tag_value": "tag.update",
    "skyvern.forge.sdk.routes.agent_protocol.reset_workflow_browser_profile": "workflow.execute",
    "skyvern.forge.sdk.routes.agent_protocol.retry_run_webhook": "workflow_run.retry",
    "skyvern.forge.sdk.routes.agent_protocol.retry_webhook": "task.retry",
    "skyvern.forge.sdk.routes.agent_protocol.retry_workflow_run": "workflow.retry",
    "skyvern.forge.sdk.routes.agent_protocol.run_block": "workflow.run",
    "skyvern.forge.sdk.routes.agent_protocol.run_task": "workflow_run.run",
    "skyvern.forge.sdk.routes.agent_protocol.run_task_v1": "task.run",
    "skyvern.forge.sdk.routes.agent_protocol.run_task_v2": "task.run",
    "skyvern.forge.sdk.routes.agent_protocol.run_workflow": "workflow.run",
    "skyvern.forge.sdk.routes.agent_protocol.run_workflow_legacy": "workflow.run",
    "skyvern.forge.sdk.routes.agent_protocol.set_workflow_template_status": "workflow.update",
    "skyvern.forge.sdk.routes.agent_protocol.suggest": "workflow.execute",
    "skyvern.forge.sdk.routes.agent_protocol.update_folder": "workflow_folder.update",
    "skyvern.forge.sdk.routes.agent_protocol.update_organization": "organization.settings.update",
    "skyvern.forge.sdk.routes.agent_protocol.update_tag_key": "tag.update",
    "skyvern.forge.sdk.routes.agent_protocol.update_tag_value": "tag.update",
    "skyvern.forge.sdk.routes.agent_protocol.update_workflow": "workflow.update",
    "skyvern.forge.sdk.routes.agent_protocol.update_workflow_folder": "workflow.update",
    "skyvern.forge.sdk.routes.agent_protocol.update_workflow_legacy": "workflow.update",
    "skyvern.forge.sdk.routes.agent_protocol.upload_file": "file.create",
    "skyvern.forge.sdk.routes.agent_protocol.webhook": "webhook.execute",
    "skyvern.forge.sdk.routes.browser_profiles.create_browser_profile": "browser_profile.create",
    "skyvern.forge.sdk.routes.browser_profiles.delete_browser_profile": "browser_profile.delete",
    "skyvern.forge.sdk.routes.browser_profiles.get_browser_profile": "browser_profile.read",
    "skyvern.forge.sdk.routes.browser_profiles.get_browser_profile_usage": "browser_profile.read",
    "skyvern.forge.sdk.routes.browser_profiles.list_browser_profiles": "browser_profile.list",
    "skyvern.forge.sdk.routes.browser_profiles.update_browser_profile": "browser_profile.update",
    "skyvern.forge.sdk.routes.browser_sessions.close_browser_session": "browser_session.execute",
    "skyvern.forge.sdk.routes.browser_sessions.create_browser_session": "browser_session.create",
    "skyvern.forge.sdk.routes.browser_sessions.create_browser_session_action_logs": "browser_session.create",
    "skyvern.forge.sdk.routes.browser_sessions.delete_pending_recording": "browser_session.delete",
    "skyvern.forge.sdk.routes.browser_sessions.extend_browser_session": "browser_session.execute",
    "skyvern.forge.sdk.routes.browser_sessions.get_browser_session": "browser_session.read",
    "skyvern.forge.sdk.routes.browser_sessions.get_browser_session_metadata": "browser_session.read",
    "skyvern.forge.sdk.routes.browser_sessions.get_browser_session_action_logs": "browser_session.list",
    "skyvern.forge.sdk.routes.browser_sessions.get_browser_sessions": "browser_session.list",
    "skyvern.forge.sdk.routes.browser_sessions.get_browser_sessions_all": "browser_session.read",
    "skyvern.forge.sdk.routes.browser_sessions.get_workflow_runs_for_browser_session": "browser_session.read",
    "skyvern.forge.sdk.routes.browser_sessions.get_workflow_version_recording": "browser_session.read",
    "skyvern.forge.sdk.routes.browser_sessions.process_recording": "browser_session.execute",
    "skyvern.forge.sdk.routes.browser_sessions.update_browser_session": "browser_session.update",
    "skyvern.forge.sdk.routes.credentials.cancel_credential_test": "credential.cancel",
    "skyvern.forge.sdk.routes.credentials.clear_org_auth_credential": "vault_provider.delete",
    "skyvern.forge.sdk.routes.credentials.create_credential": "credential.create",
    "skyvern.forge.sdk.routes.credentials.create_credential_folder": "credential_folder.create",
    "skyvern.forge.sdk.routes.credentials.delete_credential": "credential.delete",
    "skyvern.forge.sdk.routes.credentials.delete_credential_folder": "credential_folder.delete",
    "skyvern.forge.sdk.routes.credentials.get_azure_client_secret_credential": "vault_provider.read",
    "skyvern.forge.sdk.routes.credentials.get_bitwarden_credential": "vault_provider.read",
    "skyvern.forge.sdk.routes.credentials.get_credential": "credential.read",
    "skyvern.forge.sdk.routes.credentials.get_credential_folder": "credential_folder.read",
    "skyvern.forge.sdk.routes.credentials.get_credential_folders": "credential_folder.list",
    "skyvern.forge.sdk.routes.credentials.get_credential_totp_code": "credential.read",
    "skyvern.forge.sdk.routes.credentials.get_credentials": "credential.list",
    "skyvern.forge.sdk.routes.credentials.get_custom_credential_service_config": "vault_provider.read",
    "skyvern.forge.sdk.routes.credentials.get_onepassword_token": "vault_provider.read",
    "skyvern.forge.sdk.routes.credentials.get_onepassword_token_status": "vault_provider.read",
    "skyvern.forge.sdk.routes.credentials.get_test_credential_status": "credential.list",
    "skyvern.forge.sdk.routes.credentials.get_totp_codes": "credential.list",
    "skyvern.forge.sdk.routes.credentials.list_bitwarden_items": "vault_provider.list",
    "skyvern.forge.sdk.routes.credentials.list_onepassword_items": "vault_provider.list",
    "skyvern.forge.sdk.routes.credentials.rename_credential": "credential.update",
    "skyvern.forge.sdk.routes.credentials.send_totp_code": "credential.send",
    "skyvern.forge.sdk.routes.credentials.test_credential": "credential.test",
    "skyvern.forge.sdk.routes.credentials.test_custom_credential_service_connection": "credential.test",
    "skyvern.forge.sdk.routes.credentials.test_login": "credential.test",
    "skyvern.forge.sdk.routes.credentials.update_azure_client_secret_credential": "vault_provider.update",
    "skyvern.forge.sdk.routes.credentials.update_bitwarden_credential": "vault_provider.update",
    "skyvern.forge.sdk.routes.credentials.update_credential": "credential.update",
    "skyvern.forge.sdk.routes.credentials.update_credential_folder": "credential_folder.update",
    "skyvern.forge.sdk.routes.credentials.update_credential_folder_assignment": "credential_folder.update",
    "skyvern.forge.sdk.routes.credentials.update_custom_credential_service_config": "vault_provider.update",
    "skyvern.forge.sdk.routes.credentials.update_onepassword_token": "vault_provider.update",
    "skyvern.forge.sdk.routes.custom_llms.create_custom_llm": "custom_model.create",
    "skyvern.forge.sdk.routes.custom_llms.delete_custom_llm": "custom_model.delete",
    "skyvern.forge.sdk.routes.custom_llms.list_custom_llms": "custom_model.list",
    "skyvern.forge.sdk.routes.custom_llms.update_custom_llm": "custom_model.update",
    "skyvern.forge.sdk.routes.debug_sessions.get_block_outputs_for_debug_session": "debug_session.read",
    "skyvern.forge.sdk.routes.debug_sessions.get_debug_session_runs": "debug_session.list",
    "skyvern.forge.sdk.routes.debug_sessions.get_debug_session_viewer_state": "debug_session.read",
    "skyvern.forge.sdk.routes.debug_sessions.get_login_block_compatibility": "debug_session.read",
    "skyvern.forge.sdk.routes.debug_sessions.get_or_create_debug_session_by_user_and_workflow_permanent_id": "debug_session.read",
    "skyvern.forge.sdk.routes.debug_sessions.new_debug_session": "debug_session.execute",
    "skyvern.forge.sdk.routes.debug_sessions.prewarm_debug_session": "debug_session.execute",
    "skyvern.forge.sdk.routes.feedback.get_run_feedback": "feedback.read",
    "skyvern.forge.sdk.routes.feedback.submit_run_feedback": "feedback.create",
    "skyvern.forge.sdk.routes.google_oauth.delete_google_oauth_client_config": "google_oauth.delete",
    "skyvern.forge.sdk.routes.google_oauth.delete_google_oauth_credential": "google_oauth.delete",
    "skyvern.forge.sdk.routes.google_oauth.get_google_oauth_client_config": "google_oauth.read",
    "skyvern.forge.sdk.routes.google_oauth.google_oauth_authorize": "google_oauth.authorize",
    "skyvern.forge.sdk.routes.google_oauth.google_oauth_callback": "google_oauth.callback",
    "skyvern.forge.sdk.routes.google_oauth.list_google_oauth_credentials": "google_oauth.list",
    "skyvern.forge.sdk.routes.google_oauth.rename_google_oauth_credential": "google_oauth.update",
    "skyvern.forge.sdk.routes.google_oauth.update_google_oauth_client_config": "google_oauth.update",
    "skyvern.forge.sdk.routes.google_sheets.create_sheet_tab": "google_sheet.create",
    "skyvern.forge.sdk.routes.google_sheets.create_spreadsheet": "google_sheet.create",
    "skyvern.forge.sdk.routes.google_sheets.get_spreadsheet": "google_sheet.read",
    "skyvern.forge.sdk.routes.google_sheets.get_spreadsheet_dimensions": "google_sheet.list",
    "skyvern.forge.sdk.routes.google_sheets.get_spreadsheet_headers": "google_sheet.list",
    "skyvern.forge.sdk.routes.google_sheets.get_spreadsheet_tabs": "google_sheet.list",
    "skyvern.forge.sdk.routes.google_sheets.list_spreadsheets": "google_sheet.list",
    "skyvern.forge.sdk.routes.internal_auth.auth_status": "auth_session.read",
    "skyvern.forge.sdk.routes.internal_llms.llm_status": "model.read",
    "skyvern.forge.sdk.routes.microsoft_oauth.delete_microsoft_oauth_credential": "microsoft_oauth.delete",
    "skyvern.forge.sdk.routes.microsoft_oauth.list_microsoft_oauth_credentials": "microsoft_oauth.list",
    "skyvern.forge.sdk.routes.microsoft_oauth.microsoft_oauth_authorize": "microsoft_oauth.authorize",
    "skyvern.forge.sdk.routes.microsoft_oauth.microsoft_oauth_callback": "microsoft_oauth.callback",
    "skyvern.forge.sdk.routes.microsoft_oauth.rename_microsoft_oauth_credential": "microsoft_oauth.update",
    "skyvern.forge.sdk.routes.prompts.generate_workflow_title": "prompt.execute",
    "skyvern.forge.sdk.routes.prompts.improve_prompt": "prompt.execute",
    "skyvern.forge.sdk.routes.prompts.summarize_output": "prompt.execute",
    "skyvern.forge.sdk.routes.run_blocks.download_files": "workflow_run.read",
    "skyvern.forge.sdk.routes.run_blocks.login": "workflow_run.execute",
    "skyvern.forge.sdk.routes.runtime_config.get_runtime_config": "runtime_config.read",
    "skyvern.forge.sdk.routes.scripts.clear_workflow_cache": "script.delete",
    "skyvern.forge.sdk.routes.scripts.compare_script_versions": "script.read",
    "skyvern.forge.sdk.routes.scripts.create_script": "script.create",
    "skyvern.forge.sdk.routes.scripts.delete_workflow_cache_key_value": "script.delete",
    "skyvern.forge.sdk.routes.scripts.deploy_cached_script": "script.update",
    "skyvern.forge.sdk.routes.scripts.deploy_script": "script.update",
    "skyvern.forge.sdk.routes.scripts.get_fallback_episode": "script.read",
    "skyvern.forge.sdk.routes.scripts.get_fallback_episodes": "script.list",
    "skyvern.forge.sdk.routes.scripts.get_script": "script.read",
    "skyvern.forge.sdk.routes.scripts.get_script_runs": "script.list",
    "skyvern.forge.sdk.routes.scripts.get_script_version_code": "script.read",
    "skyvern.forge.sdk.routes.scripts.get_script_version_detail": "script.read",
    "skyvern.forge.sdk.routes.scripts.get_script_versions": "script.list",
    "skyvern.forge.sdk.routes.scripts.get_scripts": "script.list",
    "skyvern.forge.sdk.routes.scripts.get_workflow_cache_key_values": "script.list",
    "skyvern.forge.sdk.routes.scripts.get_workflow_script_blocks": "script.list",
    "skyvern.forge.sdk.routes.scripts.list_workflow_scripts": "script.list",
    "skyvern.forge.sdk.routes.scripts.pin_workflow_script": "script.update",
    "skyvern.forge.sdk.routes.scripts.review_script_with_instructions": "script.review",
    "skyvern.forge.sdk.routes.scripts.run_script": "script.run",
    "skyvern.forge.sdk.routes.scripts.unpin_workflow_script": "script.update",
    "skyvern.forge.sdk.routes.sdk.run_sdk_action": "sdk.run",
    "skyvern.forge.sdk.routes.self_heal.get_run_heal_episodes": "workflow_run.list",
    "skyvern.forge.sdk.routes.self_heal.get_runs_heal_summary_route": "workflow_run.read",
    "skyvern.forge.sdk.routes.self_heal.get_workflow_heal_episodes": "workflow_run.list",
    "skyvern.forge.sdk.routes.self_heal.get_workflow_reliability_route": "workflow_run.read",
    "skyvern.forge.sdk.routes.self_heal.get_workflows_reliability_route": "workflow_run.read",
    "skyvern.forge.sdk.routes.sms_inbound.receive_inbound_sms": "sms.execute",
    "skyvern.forge.sdk.routes.streaming.cdp_input.cdp_input_browser_session_stream": "browser_session.connect",
    "skyvern.forge.sdk.routes.streaming.cdp_input.cdp_input_stream": "browser_session.connect",
    "skyvern.forge.sdk.routes.streaming.messages.browser_session_messages": "stream.connect",
    "skyvern.forge.sdk.routes.streaming.messages.workflow_run_messages": "stream.connect",
    "skyvern.forge.sdk.routes.streaming.screenshot.browser_session_streaming": "stream.connect",
    "skyvern.forge.sdk.routes.streaming.screenshot.task_stream": "stream.connect",
    "skyvern.forge.sdk.routes.streaming.screenshot.workflow_run_streaming": "stream.connect",
    "skyvern.forge.sdk.routes.streaming.vnc.browser_session_stream": "browser_session.connect",
    "skyvern.forge.sdk.routes.streaming.vnc.task_stream": "browser_session.connect",
    "skyvern.forge.sdk.routes.streaming.vnc.workflow_run_stream": "browser_session.connect",
    "skyvern.forge.sdk.routes.twilio_integration.create_sms_config": "twilio.create",
    "skyvern.forge.sdk.routes.twilio_integration.create_twilio_credential": "twilio.create",
    "skyvern.forge.sdk.routes.twilio_integration.delete_sms_config": "twilio.delete",
    "skyvern.forge.sdk.routes.twilio_integration.delete_twilio_credential": "credential.delete",
    "skyvern.forge.sdk.routes.twilio_integration.disable_twilio_phone_number": "twilio.update",
    "skyvern.forge.sdk.routes.twilio_integration.enable_twilio_phone_number": "twilio.update",
    "skyvern.forge.sdk.routes.twilio_integration.get_twilio_credential": "twilio.read",
    "skyvern.forge.sdk.routes.twilio_integration.list_registered_phone_numbers": "twilio.list",
    "skyvern.forge.sdk.routes.twilio_integration.list_sms_configs": "twilio.list",
    "skyvern.forge.sdk.routes.twilio_integration.list_twilio_phone_numbers": "twilio.list",
    "skyvern.forge.sdk.routes.twilio_integration.register_manual_phone_number": "twilio.execute",
    "skyvern.forge.sdk.routes.ui_session.create_ui_session_token": "ui_session.create",
    "skyvern.forge.sdk.routes.webhooks.preview_webhook_replay": "webhook.read",
    "skyvern.forge.sdk.routes.webhooks.test_webhook": "webhook.test",
    "skyvern.forge.sdk.routes.webhooks.trigger_webhook_replay": "webhook.trigger",
    "skyvern.forge.sdk.routes.workflow_copilot.list_workflow_copilot_chats": "workflow_copilot.read",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_apply_proposed_workflow": "workflow.update",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_cancel": "workflow_copilot.manage",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_chat_audio": "workflow_copilot.manage",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_chat_history": "workflow_copilot.read",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_chat_post": "workflow.update",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_clear_proposed_workflow": "workflow_copilot.manage",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_convert_yaml_to_blocks": "workflow_copilot.manage",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_credential_deletion": "credential.delete",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_credential_generate": "credential.create",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_credential_response": "workflow_copilot.manage",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_disable_auto_accept": "workflow_copilot.manage",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_message_feedback": "workflow_copilot.manage",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_question_response": "workflow_copilot.manage",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_steer": "workflow.update",
    "skyvern.forge.sdk.routes.workflow_copilot.workflow_copilot_suggest_goal": "workflow_copilot.suggest",
    "skyvern.forge.sdk.routes.workflow_run_groups.cancel_workflow_run_group": "workflow_run.cancel",
    "skyvern.forge.sdk.routes.workflow_run_groups.get_workflow_run_group": "workflow_run.read",
    "skyvern.forge.sdk.routes.workflow_run_groups.submit_workflow_run_group": "workflow.run",
    "skyvern.forge.sdk.routes.workflow_schedules.cancel_workflow_schedule": "workflow_schedule.cancel",
    "skyvern.forge.sdk.routes.workflow_schedules.create_workflow_schedule": "workflow_schedule.create",
    "skyvern.forge.sdk.routes.workflow_schedules.delete_workflow_schedule_route": "workflow_schedule.delete",
    "skyvern.forge.sdk.routes.workflow_schedules.disable_workflow_schedule": "workflow_schedule.update",
    "skyvern.forge.sdk.routes.workflow_schedules.enable_workflow_schedule": "workflow_schedule.update",
    "skyvern.forge.sdk.routes.workflow_schedules.get_workflow_schedule": "workflow_schedule.read",
    "skyvern.forge.sdk.routes.workflow_schedules.list_organization_schedules": "workflow_schedule.list",
    "skyvern.forge.sdk.routes.workflow_schedules.list_workflow_schedules": "workflow_schedule.list",
    "skyvern.forge.sdk.routes.workflow_schedules.update_workflow_schedule": "workflow_schedule.update",
}
_REGISTERED_ROUTE_ACTIONS: dict[str, str] = {}


def register_route_actions(route_actions: Mapping[str, str]) -> None:
    _REGISTERED_ROUTE_ACTIONS.update(route_actions)


def _route_action(connection: HTTPConnection) -> tuple[str | None, dict[str, object]]:
    route = connection.scope.get("route")
    route_path = getattr(route, "path", connection.url.path)
    endpoint = getattr(route, "endpoint", None)
    handler = f"{endpoint.__module__}.{endpoint.__name__}" if endpoint else ""
    action = _REGISTERED_ROUTE_ACTIONS.get(handler)
    if action is None:
        action = ROUTE_ACTIONS.get(handler)
    resource = {"$route": route_path, **connection.path_params}
    return action, resource


async def _authorize_connection(connection: HTTPConnection) -> None:
    try:
        action, resource = _route_action(connection)
        if action is None:
            return
        decision = await app.AGENT_FUNCTION.authorize_request(get_request_principal(), action, resource)
        connection.state.authz_decision = decision
    except Exception as exc:
        LOG.warning(
            "Request authorization observation failed",
            error_type=type(exc).__name__,
            exc_info=True,
        )


async def observe_request_authorization(connection: HTTPConnection) -> AsyncIterator[None]:
    try:
        yield
    finally:
        await _authorize_connection(connection)


ROUTE_AUTHORIZATION_DEPENDENCY = Depends(observe_request_authorization, scope="function")
