{{- if and .Values.apiKey.value (not .Values.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skyvern-ui.fullname" . }}
  labels:
    {{- include "skyvern-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiKey.existingSecretKey }}: {{ .Values.apiKey.value | quote }}
{{- end }}
