from __future__ import annotations

from datetime import datetime

from sqlalchemy import func, select, update

from skyvern.forge.sdk.db._error_handling import db_operation
from skyvern.forge.sdk.db.base_repository import BaseRepository
from skyvern.forge.sdk.db.datetime_utils import naive_utc_now, to_naive_utc
from skyvern.forge.sdk.db.models import UploadedFileModel
from skyvern.forge.sdk.schemas.files import UploadedFile


class UploadedFilesRepository(BaseRepository):
    """Database operations for caller-uploaded files and their retention."""

    @db_operation("create_uploaded_file")
    async def create_uploaded_file(
        self,
        file_id: str,
        organization_id: str,
        storage_uri: str,
        filename: str,
        size_bytes: int | None = None,
        expires_at: datetime | None = None,
    ) -> UploadedFile:
        """Record an upload, superseding any live row that already claims the same URI.

        ``file_id`` is generated by the caller (before the bytes are written) so it can be
        embedded in ``storage_uri``, which keeps every row's URI unique for as long as this
        table exists. The supersede below is defense in depth for any URI collision, not the
        mechanism that prevents one: a delete reads its URI from this row, so if two live
        rows could ever share a URI, deleting either one risks the other's bytes.
        """
        now = naive_utc_now()
        async with self.Session() as session:
            await session.execute(
                update(UploadedFileModel)
                .where(UploadedFileModel.organization_id == organization_id)
                .where(UploadedFileModel.storage_uri == storage_uri)
                .where(UploadedFileModel.deleted_at.is_(None))
                .values(deleted_at=now, modified_at=now)
            )
            uploaded_file = UploadedFileModel(
                file_id=file_id,
                organization_id=organization_id,
                storage_uri=storage_uri,
                filename=filename,
                size_bytes=size_bytes,
                expires_at=to_naive_utc(expires_at),
            )
            session.add(uploaded_file)
            await session.commit()
            await session.refresh(uploaded_file)
            return UploadedFile.model_validate(uploaded_file)

    @db_operation("get_uploaded_file")
    async def get_uploaded_file(self, file_id: str, organization_id: str) -> UploadedFile | None:
        async with self.Session() as session:
            stmt = (
                select(UploadedFileModel)
                .filter_by(file_id=file_id, organization_id=organization_id)
                .filter(UploadedFileModel.deleted_at.is_(None))
            )
            result = await session.execute(stmt)
            uploaded_file = result.scalar_one_or_none()
            return UploadedFile.model_validate(uploaded_file) if uploaded_file else None

    @db_operation("attach_uploaded_files_to_run")
    async def attach_uploaded_files_to_run(
        self,
        file_ids: list[str],
        organization_id: str,
        run_id: str,
        expires_at: datetime,
    ) -> list[UploadedFile]:
        """Bind live files to a run and give them a backstop expiry, returning the rows bound.

        ``expires_at`` is only ever moved earlier. A caller who asked for a shorter
        ``retention_days`` at upload time already has a deletion promise, and attaching to a
        run must not extend the life of their data past it.

        A file already attached to a different run is left alone and omitted from the result,
        so the caller can reject the request rather than silently move an attachment (and with
        it, the deletion trigger) off the run that is still using it.
        """
        now = naive_utc_now()
        async with self.Session() as session:
            result = await session.execute(
                update(UploadedFileModel)
                .where(UploadedFileModel.file_id.in_(file_ids))
                .where(UploadedFileModel.organization_id == organization_id)
                .where(UploadedFileModel.deleted_at.is_(None))
                .where(
                    UploadedFileModel.run_id.is_(None) | (UploadedFileModel.run_id == run_id),
                )
                .values(
                    run_id=run_id,
                    expires_at=func.least(
                        func.coalesce(UploadedFileModel.expires_at, to_naive_utc(expires_at)),
                        to_naive_utc(expires_at),
                    ),
                    modified_at=now,
                )
                .returning(UploadedFileModel)
            )
            attached = [UploadedFile.model_validate(row) for row in result.scalars().all()]
            await session.commit()
            return attached

    @db_operation("get_uploaded_files_by_ids")
    async def get_uploaded_files_by_ids(self, file_ids: list[str], organization_id: str) -> list[UploadedFile]:
        async with self.Session() as session:
            stmt = (
                select(UploadedFileModel)
                .where(UploadedFileModel.file_id.in_(file_ids))
                .where(UploadedFileModel.organization_id == organization_id)
                .where(UploadedFileModel.deleted_at.is_(None))
            )
            result = await session.execute(stmt)
            return [UploadedFile.model_validate(row) for row in result.scalars().all()]

    @db_operation("get_uploaded_files_for_run")
    async def get_uploaded_files_for_run(self, run_id: str) -> list[UploadedFile]:
        async with self.Session() as session:
            stmt = (
                select(UploadedFileModel)
                .where(UploadedFileModel.run_id == run_id)
                .where(UploadedFileModel.deleted_at.is_(None))
            )
            result = await session.execute(stmt)
            return [UploadedFile.model_validate(row) for row in result.scalars().all()]

    @db_operation("claim_uploaded_file_for_deletion")
    async def claim_uploaded_file_for_deletion(self, file_id: str, organization_id: str) -> UploadedFile | None:
        """Atomically mark a live row deleted and return it, or return None if it wasn't live.

        The org predicate is part of the UPDATE rather than a separate read so a caller can
        never win a check-then-act race against a concurrent delete and issue a second
        storage delete for the same object. Exactly one caller sees the row.
        """
        now = naive_utc_now()
        async with self.Session() as session:
            result = await session.execute(
                update(UploadedFileModel)
                .where(UploadedFileModel.file_id == file_id)
                .where(UploadedFileModel.organization_id == organization_id)
                .where(UploadedFileModel.deleted_at.is_(None))
                .values(deleted_at=now, modified_at=now)
                .returning(UploadedFileModel)
            )
            uploaded_file = result.scalar_one_or_none()
            # Read the row out before committing: commit expires the ORM instance, and the
            # lazy reload that attribute access would then trigger has no greenlet to run in.
            claimed = UploadedFile.model_validate(uploaded_file) if uploaded_file else None
            await session.commit()
            return claimed

    @db_operation("get_expired_uploaded_files")
    async def get_expired_uploaded_files(self, before: datetime, limit: int = 500) -> list[UploadedFile]:
        async with self.Session() as session:
            stmt = (
                select(UploadedFileModel)
                .where(UploadedFileModel.deleted_at.is_(None))
                .where(UploadedFileModel.expires_at.isnot(None))
                .where(UploadedFileModel.expires_at <= to_naive_utc(before))
                .order_by(UploadedFileModel.expires_at)
                .limit(limit)
            )
            result = await session.execute(stmt)
            return [UploadedFile.model_validate(row) for row in result.scalars().all()]
