// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workflow_run_ids: "workflow_run_ids"
 *     }
 */
export interface BatchGetRunTagsRequest {
    /** Comma-separated workflow run IDs */
    workflow_run_ids?: string;
}
