// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateBrowserProfileRequest {
    /** Name for the browser profile */
    name: string;
    /** Optional profile description */
    description?: string;
    /** Persistent browser session to convert into a profile. Omit for a blank profile. */
    browser_session_id?: string;
    /** Workflow run whose persisted session should be captured. Omit for a blank profile. */
    workflow_run_id?: string;
}
