// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../../index.js";

/**
 * @example
 *     {
 *         name: "My Credential",
 *         credential_type: "password",
 *         credential: {
 *             password: "securepassword123",
 *             username: "user@example.com",
 *             totp: "JBSWY3DPEHPK3PXP"
 *         }
 *     }
 */
export interface CreateCredentialRequest {
    /** Name of the credential */
    name: string;
    /** Type of credential to create */
    credential_type: Skyvern.SkyvernForgeSdkSchemasCredentialsCredentialType;
    /** The credential data to store */
    credential: CreateCredentialRequest.Credential;
}

export namespace CreateCredentialRequest {
    /**
     * The credential data to store
     */
    export type Credential = Skyvern.NonEmptyPasswordCredential | Skyvern.NonEmptyCreditCardCredential;
}
