// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../../index.js";

/**
 * @example
 *     {
 *         navigation_goal: "navigation_goal"
 *     }
 */
export interface DownloadFilesRequest {
    /** Website URL */
    url?: string;
    /** Webhook URL to send status updates */
    webhook_url?: string;
    /** Proxy location to use */
    proxy_location?: Skyvern.ProxyLocation;
    /** Identifier for TOTP (Time-based One-Time Password) if required */
    totp_identifier?: string;
    /** TOTP URL to fetch one-time passwords */
    totp_url?: string;
    /** ID of the browser session to use, which is prefixed by `pbs_` e.g. `pbs_123456` */
    browser_session_id?: string;
    /** ID of a browser profile to reuse for this run */
    browser_profile_id?: string;
    /** The CDP address for the task. */
    browser_address?: string;
    /** Additional HTTP headers to include in requests */
    extra_http_headers?: Record<string, string | undefined>;
    /** Maximum number of times to scroll for screenshots */
    max_screenshot_scrolling_times?: number;
    /** Instructions for navigating to and downloading the file */
    navigation_goal: string;
    /** Suffix or complete filename for the downloaded file */
    download_suffix?: string;
    /** Timeout in seconds for the download operation */
    download_timeout?: number;
    /** Maximum number of steps to execute */
    max_steps_per_run?: number;
}
