// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../../index.js";

/**
 * @example
 *     {
 *         page: 1,
 *         page_size: 10,
 *         vault_type: "skyvern",
 *         credential_type: "password",
 *         search: "search"
 *     }
 */
export interface GetCredentialsRequest {
    /** Page number for pagination */
    page?: number;
    /** Number of items per page */
    page_size?: number;
    /** Filter credentials by vault type (e.g. 'skyvern', 'custom', 'bitwarden', 'azure_vault') */
    vault_type?: Skyvern.CredentialVaultType;
    /** Filter credentials by type (e.g. 'password', 'credit_card', 'secret') */
    credential_type?: Skyvern.SkyvernForgeSdkSchemasCredentialsCredentialType;
    /** Case-insensitive search across credential name, username, secret label, and card details */
    search?: string;
}
