// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../../index.js";

/**
 * @example
 *     {
 *         page: 1,
 *         page_size: 1,
 *         only_saved_tasks: true,
 *         only_workflows: true,
 *         only_templates: true,
 *         search_key: "search_key",
 *         title: "title",
 *         folder_id: "folder_id",
 *         template: true
 *     }
 */
export interface GetWorkflowsRequest {
    page?: number;
    page_size?: number;
    only_saved_tasks?: boolean;
    only_workflows?: boolean;
    only_templates?: boolean;
    /** Case-insensitive substring search across: workflow title, folder name, and parameter metadata (key, description, default_value). A workflow is returned if any of these fields match. Soft-deleted parameter definitions are excluded. Takes precedence over the deprecated `title` parameter. */
    search_key?: string;
    /** Deprecated: use search_key instead. Falls back to title-only search if search_key is not provided. */
    title?: string;
    /** Filter workflows by folder ID */
    folder_id?: string;
    status?: Skyvern.WorkflowStatus | Skyvern.WorkflowStatus[];
    template?: boolean;
}
