// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 1,
 *         since: "2024-01-15T09:30:00Z",
 *         key: "key"
 *     }
 */
export interface GetWorkflowTagHistoryRequest {
    /** Max events to return */
    limit?: number;
    /** Only return events at or after this timestamp */
    since?: string;
    /** Filter to events for a single tag key */
    key?: string;
}
