// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../../index.js";

/**
 * @example
 *     {
 *         credential_type: "skyvern"
 *     }
 */
export interface LoginRequest {
    /** Where to get the credential from */
    credential_type: Skyvern.SkyvernSchemasRunBlocksCredentialType;
    /** Website url */
    url?: string;
    /** Login instructions. Skyvern has default prompt/instruction for login if this field is not provided. */
    prompt?: string;
    /** Webhook URL to send login status updates */
    webhook_url?: string;
    /** Proxy location to use */
    proxy_location?: Skyvern.ProxyLocation;
    /** Identifier for TOTP (Time-based One-Time Password) if required */
    totp_identifier?: string;
    /** TOTP URL to fetch one-time passwords */
    totp_url?: string;
    /** ID of the browser session to use, which is prefixed by `pbs_` e.g. `pbs_123456` */
    browser_session_id?: string;
    /** The CDP address for the task. */
    browser_address?: string;
    /** Additional HTTP headers to include in requests */
    extra_http_headers?: Record<string, string | undefined>;
    /** Maximum number of times to scroll for screenshots */
    max_screenshot_scrolling_times?: number;
    /** ID of the Skyvern credential to use for login. */
    credential_id?: string;
    /** Bitwarden collection ID. You can find it in the Bitwarden collection URL. e.g. `https://vault.bitwarden.com/vaults/collection_id/items` */
    bitwarden_collection_id?: string;
    /** Bitwarden item ID */
    bitwarden_item_id?: string;
    /** 1Password vault ID */
    onepassword_vault_id?: string;
    /** 1Password item ID */
    onepassword_item_id?: string;
    /** Azure Vault Name */
    azure_vault_name?: string;
    /** Azure Vault username key */
    azure_vault_username_key?: string;
    /** Azure Vault password key */
    azure_vault_password_key?: string;
    /** Azure Vault TOTP secret key */
    azure_vault_totp_secret_key?: string;
}
