// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "x-max-steps-override": 1,
 *         "x-user-agent": "x-user-agent"
 *     }
 */
export interface RetryWorkflowRunRequest {
    "x-max-steps-override"?: number;
    "x-user-agent"?: string;
}
