// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../../index.js";

/**
 * @example
 *     {
 *         url: "url",
 *         action: {
 *             type: "ai_act"
 *         }
 *     }
 */
export interface RunSdkActionRequest {
    /** The URL where the action should be executed */
    url: string;
    /** The browser session ID */
    browser_session_id?: string;
    /** The browser address */
    browser_address?: string;
    /** Optional workflow run ID to continue an existing workflow run */
    workflow_run_id?: string;
    /** The action to execute with its specific parameters */
    action: Skyvern.RunSdkActionRequestAction;
}
