// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../../index.js";

/**
 * @example
 *     {}
 */
export interface TagApplyRequest {
    /** Tags to set (overwrite). List of {key?, value} objects. */
    tags?: Skyvern.TagInput[];
    /** Tags to soft-delete. List of {key?, value?} targets. */
    tags_to_delete?: Skyvern.TagDeleteInput[];
}
