// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface TagKeyUpdate {
    /** Free-form description (max 500 chars). Pass null to clear. */
    description?: string;
}
