// This file was auto-generated by Fern from our API Definition.

import type * as Skyvern from "../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateBrowserProfileRequest {
    /** New name for the browser profile */
    name?: string;
    /** New description for the browser profile */
    description?: string;
    /** Optional proxy location for this profile's pinned proxy identity. */
    proxy_location?: UpdateBrowserProfileRequest.ProxyLocation;
    /** Opaque Skyvern-managed proxy sticky-session id. */
    proxy_session_id?: string;
    /** Rotate the Skyvern-managed proxy sticky-session id for this profile. */
    rotate_proxy_session_id?: boolean;
}

export namespace UpdateBrowserProfileRequest {
    /**
     * Optional proxy location for this profile's pinned proxy identity.
     */
    export type ProxyLocation = Skyvern.ProxyLocation | Skyvern.GeoTarget | Record<string, unknown>;
}
