// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Skyvern from "../../../index.js";

export declare namespace Workflows {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Workflows {
    protected readonly _options: Workflows.Options;

    constructor(_options: Workflows.Options = {}) {
        this._options = _options;
    }

    /**
     * Get all folders for the organization
     *
     * @param {Skyvern.GetFoldersV1FoldersGetRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyvern.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.getFolders({
     *         page: 1,
     *         page_size: 1,
     *         search: "search"
     *     })
     */
    public getFolders(
        request: Skyvern.GetFoldersV1FoldersGetRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<Skyvern.Folder[]> {
        return core.HttpResponsePromise.fromPromise(this.__getFolders(request, requestOptions));
    }

    private async __getFolders(
        request: Skyvern.GetFoldersV1FoldersGetRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<Skyvern.Folder[]>> {
        const { page, page_size: pageSize, search } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (pageSize != null) {
            _queryParams.page_size = pageSize.toString();
        }

        if (search != null) {
            _queryParams.search = search;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyvernEnvironment.Cloud,
                "v1/folders",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyvern.Folder[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new Skyvern.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyvernError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyvernError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyvernTimeoutError("Timeout exceeded when calling GET /v1/folders.");
            case "unknown":
                throw new errors.SkyvernError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new folder to organize workflows
     *
     * @param {Skyvern.FolderCreate} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyvern.BadRequestError}
     * @throws {@link Skyvern.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.createFolder({
     *         title: "title"
     *     })
     */
    public createFolder(
        request: Skyvern.FolderCreate,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<Skyvern.Folder> {
        return core.HttpResponsePromise.fromPromise(this.__createFolder(request, requestOptions));
    }

    private async __createFolder(
        request: Skyvern.FolderCreate,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<Skyvern.Folder>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyvernEnvironment.Cloud,
                "v1/folders",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyvern.Folder, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Skyvern.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Skyvern.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyvernError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyvernError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyvernTimeoutError("Timeout exceeded when calling POST /v1/folders.");
            case "unknown":
                throw new errors.SkyvernError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a specific folder by ID
     *
     * @param {string} folderId - Folder ID
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyvern.NotFoundError}
     * @throws {@link Skyvern.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.getFolder("fld_123")
     */
    public getFolder(
        folderId: string,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<Skyvern.Folder> {
        return core.HttpResponsePromise.fromPromise(this.__getFolder(folderId, requestOptions));
    }

    private async __getFolder(
        folderId: string,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<Skyvern.Folder>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyvernEnvironment.Cloud,
                `v1/folders/${core.url.encodePathParam(folderId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyvern.Folder, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyvern.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Skyvern.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyvernError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyvernError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyvernTimeoutError("Timeout exceeded when calling GET /v1/folders/{folder_id}.");
            case "unknown":
                throw new errors.SkyvernError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Update a folder's title or description
     *
     * @param {string} folderId - Folder ID
     * @param {Skyvern.FolderUpdate} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyvern.NotFoundError}
     * @throws {@link Skyvern.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.updateFolder("fld_123")
     */
    public updateFolder(
        folderId: string,
        request: Skyvern.FolderUpdate = {},
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<Skyvern.Folder> {
        return core.HttpResponsePromise.fromPromise(this.__updateFolder(folderId, request, requestOptions));
    }

    private async __updateFolder(
        folderId: string,
        request: Skyvern.FolderUpdate = {},
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<Skyvern.Folder>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyvernEnvironment.Cloud,
                `v1/folders/${core.url.encodePathParam(folderId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyvern.Folder, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyvern.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Skyvern.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyvernError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyvernError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyvernTimeoutError("Timeout exceeded when calling PUT /v1/folders/{folder_id}.");
            case "unknown":
                throw new errors.SkyvernError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a folder. Optionally delete all workflows in the folder.
     *
     * @param {string} folderId - Folder ID
     * @param {Skyvern.DeleteFolderV1FoldersFolderIdDeleteRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyvern.NotFoundError}
     * @throws {@link Skyvern.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.deleteFolder("fld_123", {
     *         delete_workflows: true
     *     })
     */
    public deleteFolder(
        folderId: string,
        request: Skyvern.DeleteFolderV1FoldersFolderIdDeleteRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<Record<string, unknown>> {
        return core.HttpResponsePromise.fromPromise(this.__deleteFolder(folderId, request, requestOptions));
    }

    private async __deleteFolder(
        folderId: string,
        request: Skyvern.DeleteFolderV1FoldersFolderIdDeleteRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, unknown>>> {
        const { delete_workflows: deleteWorkflows } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (deleteWorkflows != null) {
            _queryParams.delete_workflows = deleteWorkflows.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyvernEnvironment.Cloud,
                `v1/folders/${core.url.encodePathParam(folderId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, unknown>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyvern.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Skyvern.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyvernError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyvernError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyvernTimeoutError("Timeout exceeded when calling DELETE /v1/folders/{folder_id}.");
            case "unknown":
                throw new errors.SkyvernError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Update a workflow's folder assignment for the latest version
     *
     * @param {string} workflowPermanentId - Workflow permanent ID
     * @param {Skyvern.UpdateWorkflowFolderRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyvern.BadRequestError}
     * @throws {@link Skyvern.NotFoundError}
     * @throws {@link Skyvern.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.updateWorkflowFolder("wpid_123")
     */
    public updateWorkflowFolder(
        workflowPermanentId: string,
        request: Skyvern.UpdateWorkflowFolderRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<Skyvern.Workflow> {
        return core.HttpResponsePromise.fromPromise(
            this.__updateWorkflowFolder(workflowPermanentId, request, requestOptions),
        );
    }

    private async __updateWorkflowFolder(
        workflowPermanentId: string,
        request: Skyvern.UpdateWorkflowFolderRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<Skyvern.Workflow>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyvernEnvironment.Cloud,
                `v1/workflows/${core.url.encodePathParam(workflowPermanentId)}/folder`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyvern.Workflow, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Skyvern.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Skyvern.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Skyvern.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyvernError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyvernError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyvernTimeoutError(
                    "Timeout exceeded when calling PUT /v1/workflows/{workflow_permanent_id}/folder.",
                );
            case "unknown":
                throw new errors.SkyvernError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
