apiVersion: v1
kind: Secret
metadata:
  name: skyvern-backend-env
  namespace: skyvern
type: Opaque
stringData:
  # Environment variables for the Skyvern backend
  # You can use the ones from the .env file in the root of skyvern
  ENV: local
  ENABLE_OPENAI: ""
  OPENAI_API_KEY: ""
  ENABLE_ANTHROPIC: "false"
  ANTHROPIC_API_KEY: ""
  ENABLE_AZURE: "false"
  AZURE_DEPLOYMENT: ""
  AZURE_API_KEY: ""
  AZURE_API_BASE: ""
  AZURE_API_VERSION: ""
  ENABLE_AZURE_GPT4O_MINI: "false"
  AZURE_GPT4O_MINI_DEPLOYMENT: ""
  AZURE_GPT4O_MINI_API_KEY: ""
  AZURE_GPT4O_MINI_API_BASE: ""
  AZURE_GPT4O_MINI_API_VERSION: ""
  ENABLE_GEMINI: "false"
  GEMINI_API_KEY: ""
  ENABLE_NOVITA: "false"
  NOVITA_API_KEY: ""
  LLM_KEY: OPENAI_GPT4_1
  SECONDARY_LLM_KEY: ""
  BROWSER_TYPE: chromium-headless
  MAX_SCRAPING_RETRIES: "0"
  VIDEO_PATH: ./videos
  BROWSER_ACTION_TIMEOUT_MS: "5000"
  MAX_STEPS_PER_RUN: "50"
  LOG_LEVEL: INFO
  LITELLM_LOG: CRITICAL
  DATABASE_STRING: postgresql+psycopg://skyvern:skyvern@postgres/skyvern
  PORT: "8000"
  ANALYTICS_ID: ""
  ENABLE_LOG_ARTIFACTS: "false"
  ENABLE_OPENAI_COMPATIBLE: "false"
  SKYVERN_BASE_URL: http://localhost:8000
  SKYVERN_API_KEY: ""
