"""Public API reference taxonomy (SKY-10580).

docs/api-reference/openapi.json is generated by scripts/sync_openapi_docs.py and rendered by
Mintlify, one section per OpenAPI tag. These tests pin the organization decisions so a future route
change can't silently reintroduce a lowercase/legacy tag or split the agent sub-resources back out.

They assert against the committed spec only — the exact static artifact Mintlify renders. Building
the app here instead (create_api_app / base_router) would couple the tests to global router state
that other tests in the same process can pollute (a stale "Workflow Tags" route leaks in across
shards), so the spec on disk is the one source that is deterministic regardless of suite order.
Drift between the code and this file is caught separately: the PR-review reminder, the OpenAPI docs
sync workflow, and `scripts/sync_openapi_docs.py --check`.
"""

import json
from pathlib import Path

COMMITTED_SPEC = Path(__file__).resolve().parents[2] / "docs" / "api-reference" / "openapi.json"

# Capitalized resource tags — kept in lockstep with .claude/skills/api-docs-audit/SKILL.md.
APPROVED_TAGS = {
    "Agents",
    "Folders",
    "Tags",
    "Schedules",
    "Credentials",
    "Browser Sessions",
    "Browser Profiles",
    "Artifacts",
    "Files",
    "Scripts",
    "Server",
    "SDK",
    "Runs",
}
# Pre-rebrand / internal tags that must never render a public section again.
RETIRED_TAGS = {
    "Agent Folders",
    "Agent Tags",
    "Workflow Folders",
    "Workflow Tags",
    "Workflows",
    "Workflow Runs",
    "server",
    "scheduler",
}
# The endpoints this change re-tagged → their clean resource tag.
RETAGGED_PATH_TAGS = {
    "/v1/folders": "Folders",
    "/v1/folders/{folder_id}": "Folders",
    "/v1/agents/{workflow_permanent_id}/tags": "Tags",
    "/v1/tag-keys": "Tags",
    "/v1/tag-keys/{key}": "Tags",
    "/v1/version": "Server",
    "/v1/run/agents": "Runs",
    "/v1/runs/{run_id}": "Runs",
    "/v1/runs/cancel": "Runs",
    "/v1/agents/runs": "Runs",
    "/v1/agents/{workflow_id}/runs": "Runs",
}


def _committed_spec() -> dict:
    return json.loads(COMMITTED_SPEC.read_text())


def _visible_tags(spec: dict) -> set[str]:
    # x-hidden ops stay in the schema (Fern keeps them) but Mintlify never renders them, so a
    # lowercase tag on a hidden op is fine — only non-hidden ops drive the rendered sections.
    return {
        tag
        for methods in spec["paths"].values()
        for op in methods.values()
        if isinstance(op, dict) and not op.get("x-hidden")
        for tag in (op.get("tags") or [])
    }


def test_no_lowercase_visible_tags() -> None:
    lowercase = sorted(t for t in _visible_tags(_committed_spec()) if t[:1].islower())
    assert lowercase == [], f"lowercase tags render as sloppy doc sections: {lowercase}"


def test_visible_tags_are_approved_resource_names() -> None:
    tags = _visible_tags(_committed_spec())
    assert {"Folders", "Tags", "Server"} <= tags, "the public sub-resources must each keep a section"
    assert tags <= APPROVED_TAGS, (
        f"unapproved tag(s) — justify and add to APPROVED_TAGS: {sorted(tags - APPROVED_TAGS)}"
    )
    assert tags.isdisjoint(RETIRED_TAGS)


def test_retagged_endpoints_use_clean_tags() -> None:
    spec = _committed_spec()
    for path, expected in RETAGGED_PATH_TAGS.items():
        for method, op in spec["paths"][path].items():
            if isinstance(op, dict):
                assert op.get("tags") == [expected], f"{method.upper()} {path} tags={op.get('tags')}"


def test_version_endpoint_is_conformant() -> None:
    op = _committed_spec()["paths"]["/v1/version"]["get"]
    assert op["tags"] == ["Server"]
    assert op["x-fern-sdk-method-name"] == "get_version"
