name: Codeflash
on:
  pull_request:
    paths:
      # So that this workflow only runs when code within the target module is modified
      - "skyvern/**"
  workflow_dispatch:
concurrency:
  # Any new push to the PR will cancel the previous run, so that only the latest code is optimized
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  optimize:
    name: Optimize new Python code in this PR
    if: ${{ github.actor != 'codeflash-ai[bot]' }}
    runs-on: ubuntu-latest
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      CODEFLASH_PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Sync project dependencies
        run: |
          uv sync --group dev
      - name: Install Codeflash into venv
        run: |
          uv pip install codeflash
      - name: Create test dir
        run: mkdir -p codeflash-tests
      - name: Run Codeflash to optimize code
        run: uv run codeflash
      - name: remove test dir
        run: |-
          rm -rf codeflash-tests
