# .github/workflows/sync-skyvern-main.yml

name: Sync with Main

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow automatically every day at 10:00 UTC
  schedule:
    - cron: "0 10 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/skyvern-ai/skyvern.git

      - name: Fetch from Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: git merge upstream/main -m "Merge upstream changes" || true

      # Ensure docker-compose.yml is deleted if it exists
      - name: Ensure docker-compose.yml is deleted
        run: |
          if [ -f docker-compose.yml ]; then
            git rm -f docker-compose.yml
          fi

      # Stage docker-compose.yaml, if it exists
      - name: Stage preserved file
        run: |
          if [ -f docker-compose.yaml ]; then
            git add docker-compose.yaml
          fi

      # Remove unwanted workflow files from upstream, only if they exist
      - name: Remove unwanted upstream workflows
        run: |
          if [ -f .github/workflows/build-docker-image.yml ]; then
            git rm -f .github/workflows/build-docker-image.yml
          fi
          if [ -f .github/workflows/sync-skyvern-cloud.yml ]; then
            git rm -f .github/workflows/sync-skyvern-cloud.yml
          fi

      # (REMOVED) Restore local frontend/package.json step

      # Restore frontend/dockerfile.artifact if missing
      - name: Restore frontend/dockerfile.artifact if missing
        run: |
          if [ ! -f frontend/dockerfile.artifact ]; then
            git checkout origin/main -- frontend/dockerfile.artifact || touch frontend/dockerfile.artifact
          fi

      - name: Commit changes
        run: |
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: Sync with upstream and preserve docker-compose.yaml, frontend/package.json, and dockerfile.artifact"
          fi

      - name: Push changes
        run: git push origin main
